Ajout d'une page commune
BaseAdresseNationale/adresse.data.gouv.fr pull request #1008
Opened 2022-01-25 14:55 UTC by Maxine-Le-Pennec

Création d'une page commune contenant des informations sur les adresses de la commune.

### Attention
**Cette branche fonctionne avec [l'api dépôt](https://github.com/BaseAdresseNationale/api-depot/wiki/Documentation) et la mise à jour de l'api bal ([PR  Système de synchronisation avec la BAN](https://github.com/BaseAdresseNationale/api-bal/pull/303))**

Tester la page avec la maj de l'api ban et l'api dépôt en local :

**API-DEPOT :**
- Créer un fichier `clients.yml` en suivant le model de `clients.yml.sample`
- Changer le port dans `server.js` pour éviter les conflits
- Créer `.env` avec SHOW_EMAILS=YES

**API-BAL :**
- Aller sur la branche jdesboeufs/api-depot
- Créer un .env avec : 

```
MONGODB_URL=mongodb://localhost:27017  //pas toucher
MONGODB_DBNAME=api-bal  //pas toucher
PORT=5000  //pas toucher
SMTP_HOST=  //pas toucher
SMTP_PORT=587  //pas toucher
SHOW_EMAILS=YES  //pas toucher
EDITOR_URL_PATTERN=https://mes-adresses.data.gouv.fr/bal/<id>/<token> //pas toucher
BAN_SOURCE_URL_PATTERN=https://adresse.data.gouv.fr/data/ban/adresses-odbl/latest/csv/adresses-<codeDepartement>.csv.gz  //pas toucher
API_URL=http://localhost:5000/v1  //pas toucher
RUN_MIGRATION=0  //pas toucher
API_DEPOT_URL=http://localhost:<port de l’api depot>
API_DEPOT_CLIENT_ID= <le valeur de nom du fichier clients.yml>
API_DEPOT_CLIENT_SECRET=<le valeur de token du fichier clients.yml>
```

**MES-ADRESSES**

- Aller sur la branche tmerlier/redesign-contexte-loading
- Dans ban-api.js, changer le port par  const BAN_API_DEPOT = process.env.NEXT_PUBLIC_BAN_API_DEPOT || <http://localhost:<port de l’api depot>

- Lancer le tout, créer et publier plusieurs (deux par exemple) BAL sur mes-adresses pour une commune choisie. Utiliser le code d’habilitation apparaissant dans la console de l’api-depot.
- Tester la page de cette commune sur adresse.data.
- Tester la page commune sans BAL.

### Infos générales de la commune
<img width="1440" alt="Capture d’écran 2022-01-25 à 15 14 26" src="https://user-images.githubusercontent.com/66621960/150997373-60c920f3-d5ef-4375-8f15-ded5afd56af1.png">

### État des adresses et contact de la commune
<img width="1440" alt="Capture d’écran 2022-01-25 à 15 14 38" src="https://user-images.githubusercontent.com/66621960/150997379-97bdc86f-7d63-44d6-8209-045c40e9c390.png">
<img width="1440" alt="Capture d’écran 2022-01-25 à 15 17 18" src="https://user-images.githubusercontent.com/66621960/150997382-254f9ca6-848b-4554-8247-b48a5e0119e6.png">

### Qualité des adresses
<img width="1440" alt="Capture d’écran 2022-01-25 à 15 26 40" src="https://user-images.githubusercontent.com/66621960/150997384-d824f242-d872-49e5-89fd-a2c4da64e804.png">
<img width="1440" alt="Capture d’écran 2022-01-25 à 15 27 01" src="https://user-images.githubusercontent.com/66621960/150997387-44b56b99-35d0-4f9a-ab0f-32cc92a3c94d.png">
<img width="1440" alt="Capture d’écran 2022-01-25 à 15 29 59" src="https://user-images.githubusercontent.com/66621960/150997388-e6b38713-24db-4540-8548-de87486a9667.png">

### Historique de révision de la BAL
<img width="1440" alt="Capture d’écran 2022-01-25 à 15 27 09" src="https://user-images.githubusercontent.com/66621960/150997391-5cb0d45c-a481-4513-9bd0-f6a9fb2c086f.png">
<img width="1440" alt="Capture d’écran 2022-01-25 à 15 31 21" src="https://user-images.githubusercontent.com/66621960/150997394-e881730d-a365-4db5-996a-e0e676ad501e.png">

2022-02-02 12:57 UTC, jdesboeufs commented on .env.sample
> +NEXT_PUBLIC_BAL_API_URL=https://api-bal.adresse.data.gouv.fr/v1
Où est utilisée cette variable ?

2022-02-02 13:11 UTC, jdesboeufs commented
Je ne comprends pas quelle est l'adhérence avec les autres chantiers sur l'API BAL.

2022-02-02 14:47 UTC, GllmR requested changes

2022-02-02 14:47 UTC, GllmR commented on components/commune/bal-state.js
> +            <p>La commune de Beauvoir-sur-Mer ne dispose d’aucune Base Adresse Locale.</p>
Pourquoi ne pas utiliser le nom de la commune ici ?

2022-02-02 14:47 UTC, GllmR commented on components/commune/commune-infos.js
> +            <div>{codesPostaux.map(code => <span className='value' key={code}>{code}</span>)}</div>
Il peut y avoir plusieurs codes postaux. 
Je ne suis pas convaincu par l'affichage en liste des codes, qui prennent beaucoup de place.

2022-02-02 14:47 UTC, GllmR commented on components/commune/historique.js
> +  })
Tu dois pouvoir utiliser [lodash](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/blob/60be5253908ea6c45a4d5748d78f29f0ae284e40/package.json#L32) pour simplifier ça

2022-02-03 08:47 UTC, Maxine-Le-Pennec commented on .env.sample
> +NEXT_PUBLIC_BAL_API_URL=https://api-bal.adresse.data.gouv.fr/v1
J'ai oublié de virer cette variable suite à une fausse route sur l'utilisation de l'API

2022-02-03 08:49 UTC, Maxine-Le-Pennec commented on components/commune/commune-infos.js
> +            <div>{codesPostaux.map(code => <span className='value' key={code}>{code}</span>)}</div>
Je vais utiliser le premier code postal. Jérôme m'a proposé d'afficher soit la liste complète, soit juste le premier de la liste et en effet, une liste complète ça fait un peu lourdingue

2022-02-07 23:26 UTC, jdesboeufs approved these changes

2022-02-07 23:28 UTC, merged