[W.I.P] Migration du Blog vers Adresse
BaseAdresseNationale/adresse.data.gouv.fr pull request #1010
Opened 2022-01-27 15:36 UTC by GllmR

**⚠️ Cette Pull Request ne fonctionnera pas tant que la nouvelle version du blog n'est pas en ligne ⚠️**

# Migration du Blog vers le site adresse.data.gouv.fr

## Contexte : 

Le blog est actuellement hébergé sur un blog [Medium](https://medium.com/), à l'adresse [blog.geo.data.gouv.fr](blog.geo.data.gouv.fr).
L'utilisation de Medium ne permet pas d'afficher de manière simple les articles du blog sur le site Adresse.
Une page `/temoignages` permet d'afficher une partie des articles, il faut malheureusement l'intervention d'un développeur pour mettre à jour le fichier à chaque nouvel article.

## Solution : 

Nous avons décidé d'utiliser [Ghost](https://ghost.org/) pour la création des articles.
Il offre plusieurs [avantages](https://ghost.org/vs/medium/) par rapport à Medium : Il est [libre](https://github.com/tryghost/ghost/), il est très simple d'utilisation, il est simple de l'héberger et il fournit une [API](https://ghost.org/docs/content-api/) donnant accès aux articles.

Les articles seront donc rédigés sur le blog Ghost et importés automatiquement, grâce à l'API, vers la page `/blog` du site Adresse.

Cela permet d'avoir des outils pour rédiger les articles simplement, puis de les afficher sur le site Adresse sans l'intervention d'un développeur.

### Code : 
L'utilisation de l'API Ghost pose quelques contraintes : 
- Ajout d’un `dangerouslySetInnerHTML` : Pour afficher le contenu de l'article
- Ajout d'un style global `blog.css` : Obligatoire pour que les styles fonctionnent sur le contenu des articles, particulièrement pour les images.

## Utilisation de cette branche : 

Pour tester cette branche, il est nécessaire de remplir les champs dans le fichier `.env` : 
- L'URL du site Ghost
- Le domaine du site Ghost pour l'optimisation des images
- Le token permettant d'accéder aux articles du blog

## Captures : 

![image](https://user-images.githubusercontent.com/56537238/151390639-b5f2b497-d911-4775-b09b-103786a86ea0.png)

![image](https://user-images.githubusercontent.com/56537238/151390869-ba4c75da-9941-49b7-813c-109e310705b2.png)

2022-02-23 12:47 UTC, tmerlier requested changes

2022-02-23 12:47 UTC, tmerlier commented on pages/blog/index.js
> +BlogIndex.getInitialProps = async () => {
Même remarque que pour les autres page, `getStaticProps ` serait plus approprié.

2022-02-24 11:17 UTC, GllmR commented on pages/bases-locales/temoignages/[slug].js
> +  return {post: post?.posts[0]}
Et oui 🤷 
Je vais regarder pour modifier la fonction, mais c'est le fonctionnement de l'API Ghost.

2022-02-28 16:27 UTC, tmerlier requested changes

2022-02-28 16:47 UTC, GllmR commented on components/temoignages.js
> +  posts: PropTypes.array
Je l'ai laissé en `null` par défaut dans le cas où le blog n’est pas accessible.

2022-03-04 16:29 UTC, tmerlier approved these changes

2022-03-04 16:30 UTC, merged