Amélioration de la bannière évènements page d'accueil
BaseAdresseNationale/adresse.data.gouv.fr pull request #1059
Opened 2022-03-01 11:23 UTC by Maxine-Le-Pennec

Affichage des trois évènements prévus, du premier à venir au dernier, via un système de slides.
Changement de slide via un timer et un système de contrôle manuel.

Indique le nom de l'évènement, la date. Affiche la modale avec la totalité des informations lors du click sur le nom de l'évènement.

https://user-images.githubusercontent.com/66621960/156159737-c5f34c90-f13a-4612-954f-9606c69e649a.mov
![Capture d’écran 2022-03-01 à 11 02 37](https://user-images.githubusercontent.com/66621960/156160087-99cb6edd-0bbc-4404-8acb-319d9abe8a5d.png)
![Capture d’écran 2022-03-01 à 12 12 34](https://user-images.githubusercontent.com/66621960/156160091-6c9aebf8-4610-4626-a8c1-c491be3cd05e.png)

2022-03-01 14:43 UTC, GllmR approved these changes

2022-03-01 15:06 UTC, tmerlier requested changes

2022-03-01 15:06 UTC, tmerlier commented on components/evenement/event-banner.js
> +  const selectedFirstEvents = sortEventsByDate(events, 'asc').filter(event => new Date(event.date).setHours(0, 0, 0, 0) >= today).slice(0, 3)
`selectedFirstEvents` pourrait simplement se nommer `events` dans ce contexte.

2022-03-01 15:06 UTC, tmerlier commented on components/evenement/event-banner.js
> +          </ul>
Autant ne pas afficher de bannière du tout je pense.

2022-03-01 15:06 UTC, tmerlier commented on components/evenement/event-banner.js
> +          })
Pourquoi faire un `map` si qu'un seul élément est rendu au final ?

2022-03-04 15:11 UTC, tmerlier approved these changes

2022-03-04 15:30 UTC, merged