Correction des liens vers le Blog & nettoyage
BaseAdresseNationale/adresse.data.gouv.fr pull request #1069
Opened 2022-03-07 11:30 UTC by GllmR

Corrige quelques petits oublis après mise en ligne du Blog : 
- Corrige les liens vers le blog (`blog.geo.data.gouv` ⇾ `/blog`)
- Enlève un `next/link` inutile
- Supprime le fichier `temoignages.json` qui n’est plus utilisé (remplacé par les articles du blog contenant le mot-clé `temoignage`)

Fix #1068 

Linked to #1010

2022-03-07 11:44 UTC, Maxine-Le-Pennec approved these changes

2022-03-07 13:57 UTC, jdesboeufs requested changes
Quid des témoignages qui ne sont pas hébergés sur le blog ?

2022-03-08 17:19 UTC, GllmR commented
> Quid des témoignages qui ne sont pas hébergés sur le blog ?

Sophie a ajouté les articles manquants sur le blog, le fichier n’est donc plus nécessaire.

2022-03-16 10:38 UTC, jdesboeufs approved these changes

2022-03-16 10:56 UTC, merged