Prise en charge du CSS des blocs du blog Ghost
BaseAdresseNationale/adresse.data.gouv.fr pull request #1087
Opened 2022-03-21 16:39 UTC by GllmR

## Prise en charge du CSS des blocs Ghost :  

Les articles en provenance du blog Ghost utilisent certaines classes CSS spéciales qui n’étaient pas prises en charge, créant un affichage chaotique.

Cette PR propose la prise en charge des blocs Ghost principaux : 
- Bookmark (MAJ)
- Image
- Gallery
- HTML
- Markdown
- Divider
- Button
- Toggle
- Header
- File
- Video
- Audio 
- Callout
- Product

2022-03-21 17:28 UTC, tmerlier requested changes

2022-03-21 17:28 UTC, tmerlier commented on components/post.js
> +          d.addEventListener('click', () => {
Il faut également le `removeEventListener` lors du démontage du composant.

2022-03-21 17:28 UTC, tmerlier commented on components/post.js
> +    if (html) {
`html` devrait toujours être défini et n'a donc normalement pas besoin d'être vérifié.

2022-03-21 17:28 UTC, tmerlier commented on components/post.js
> +import colors from '@/styles/colors'
Il manque un saut de ligne.

2022-03-21 17:28 UTC, tmerlier commented on components/post.js
> +      if (videoPlayer) {
Sera toujours vrai, car `videoPLayer` est défini comme un `Array` plus haut.

2022-03-21 17:28 UTC, tmerlier commented on components/post.js
> +      if (audioPlayer) {
Même problème que pour `videoPlayer` ici.

2022-03-21 17:28 UTC, tmerlier commented on components/post.js
> +      if (dropdownDiv) {
Même problème que `audioPlayer` et `videoPlayer`.

2022-03-22 10:11 UTC, Maxine-Le-Pennec reviewed
Concernant le responsive de ce bloc, je pense qu'il serait peut-être plus harmonieux de faire passer le bouton de téléchargement en dessus (passer en colonnes).
![Capture d’écran 2022-03-22 à 11 09 26](https://user-images.githubusercontent.com/66621960/159457234-b0ef06f5-c362-45b9-8acf-934c88fcfa6a.png)

2022-03-22 10:13 UTC, Maxine-Le-Pennec commented
Les images se croppent passé une certaine taille d'écran
![Capture d’écran 2022-03-22 à 11 11 54](https://user-images.githubusercontent.com/66621960/159457755-301bcb26-616e-4f30-9e49-711d22797687.png)

2022-03-22 10:51 UTC, Maxine-Le-Pennec commented
Il faudrait peut être désactivé la règle xo afin d'éviter les multiples warnings
![Capture d’écran 2022-03-22 à 11 50 19](https://user-images.githubusercontent.com/66621960/159465719-ac5fe4d4-197d-4548-b2cc-5ab07f934e7c.png)

2022-03-22 16:59 UTC, Maxine-Le-Pennec approved these changes

2022-03-25 09:53 UTC, tmerlier approved these changes

2022-03-29 08:21 UTC, merged