Amélioration du modèle json pour les partenaires
BaseAdresseNationale/adresse.data.gouv.fr pull request #1100
Opened 2022-03-28 09:15 UTC by Maxine-Le-Pennec

Afin d'accueillir le nouveau type de partenaires de la Charte (communes), une réorganisation du JSON contenant les partenaires permet de faciliter le développement en proposant un code plus lisible et mieux organisé. 
Il est à présent possible de distinguer les epci, entreprises et communes disposant chacun de leur tableau avec la liste des partenaires correspondants.

2022-03-28 09:59 UTC, tmerlier requested changes

2022-03-28 09:59 UTC, tmerlier commented on components/bases-locales/charte/partners.js
> +  const companiesPartners = companies && orderByName(companies)
La fonction `orderByName` n'est pas vraiment nécessaire, `orderBy` peut être utilisé comme ceci
```suggestion
  const companiesPartners = companies && orderBy(companies, 'name', 'asc')
```

2022-03-28 09:59 UTC, tmerlier commented on components/bases-locales/charte/partners.js
>  Partner.defaultProps = {
```suggestion
Partners.defaultProps = {
```

2022-03-28 09:59 UTC, tmerlier commented on components/bases-locales/index.js
> +    const randomizedPartners = shuffle(allPartners).slice(0, 3)
```suggestion
    const randomizedPartners = shuffle([...partners.companies, ...partners.epci]).slice(0, 3)
```

2022-03-28 12:41 UTC, GllmR approved these changes

2022-03-29 07:15 UTC, tmerlier approved these changes

2022-03-29 07:27 UTC, merged