Refonte de la présentation des partenaires
BaseAdresseNationale/adresse.data.gouv.fr pull request #1109
Opened 2022-04-01 15:58 UTC by Maxine-Le-Pennec

Suite à l'ajout des communes parmi les partenaires de la charte, les sections présentant les partenaires ont été entièrement remaniés.

- **la page `/charte`** : présente les deux chartes (celle concernant les epci/entreprises et celle concernant les communes) et redirige vers deux nouvelles pages : `charte/communes` et `charte/organismes`.

- **Page `charte/communes`** : dispatche les communes partenaires dans la bonne région et le bon département. La première liste affiche toutes les régions et la seconde n'affiche que les départements ayant une commune partenaire sur son territoire. Ce mode d'affichage permet d'éviter de surcharger la page avec une trop grande quantité de départements affichés ou une liste de communes qui pourraient être, à terme, très longue.

- **Page `charte/organismes`** : Reprend l'affichage des partenaires tels qu'ils étaient présentés dans la version précédente.

- Ajout des communes partenaires dans la barre de recherche des partenaires avec un design différent des autres pour une meilleure distinction.

### Améliorations pour la suite : 
Afficher plus d'informations sur la commune telles que le lien vers sa BAL
![page-charte](https://user-images.githubusercontent.com/66621960/161299506-6fe36d21-8421-465f-93ad-1fd16be9a829.jpg)
![page-commune](https://user-images.githubusercontent.com/66621960/161299520-7d2487b4-2a32-42b1-90f6-b9b0188f517d.jpg)
![page-organismes](https://user-images.githubusercontent.com/66621960/161299524-221829a0-bb8d-44e0-a6c3-b1855efd46d4.jpg)
![barre-recherche](https://user-images.githubusercontent.com/66621960/161299532-d60829e4-e608-4ccb-8958-562558b5abe5.jpg)

2022-04-04 10:13 UTC, tmerlier commented
## Revue fonctionnelle
### Liste des communes partenaires

- Il y a pour le moment trop de région sans commune partenaire, il serait préférable de lister en priorité les régions avec des résultats
![Capture d’écran 2022-04-04 à 11 44 55](https://user-images.githubusercontent.com/7040549/161518605-4294f4b8-ca98-4e78-9b97-4da116c2c1f5.png)
- Seule la flèche en est cliquable et permet de déplier une région. Étant la seule action possible, il serait plus pratique de l'étendre à toute la section
- Ajouter un effet de survole sur les sections afin de faire comprendre qu'une action est possible
- Ajouter les informations de contact de commune en plus du lien vers sa page

2022-04-04 10:56 UTC, tmerlier requested changes
Je trouve la séparation du JSON des différents types de partenaires finalement peu utile dans le code. On se retrouve quasiment tout le temps à reformer l'ancien assemblage en faisant `[...partners.epci, ...partners.companies, ...partners.communes]`

2022-04-04 10:56 UTC, tmerlier commented on components/bases-locales/charte/partner.js
> +  }, [isCommune, codeCommune])
Il faut prévoir un chargement pour la récupération de cette info.

2022-04-04 10:56 UTC, tmerlier commented on components/bases-locales/charte/partner.js
> +              <ChevronDown size={18} color={`${theme.colors.lightBlue}`} />
Nous pourrions calculer le bon composant icône à utiliser afin de ne pas dupliquer le code.

`const Chevron = isOpen ? ChevronUp : ChevronDown`

2022-04-04 10:56 UTC, tmerlier commented on components/bases-locales/charte/partner.js
> +          )}
```suggestion
          <p>{isDisplay ? 'Masquer' : 'Afficher'} les informations</p>
```

2022-04-04 10:56 UTC, tmerlier commented on components/bases-locales/charte/partner.js
> +          </div>
Créer un composant `MairieContact` réutilisable serait une bonne idée je pense.

2022-04-04 10:56 UTC, tmerlier commented on components/card.js
> +  children: PropTypes.node,
Le rendu laisse penser que `children` est obligatoire.

2022-04-04 10:56 UTC, tmerlier commented on components/bases-locales/charte/partners-searchbar.js
> +  const organizationPartners = filteredPartners.filter(partner => !partner.isCompany && partner.echelon !== 0)
Il faut au moins utiliser `useMemo` pour ces variables, mais je pense que l'implémentation est à revoir.

2022-04-04 10:56 UTC, tmerlier commented on components/bases-locales/charte/partners-searchbar.js
> +      <p className='searchbar-label'>Recherchez un partenaire de la Charte de la Base Adresse Locale dans votre département</p>
Pourquoi avoir modifié le wording ici ?

2022-04-04 10:56 UTC, tmerlier commented on components/bases-locales/charte/region.js
> +  const fetchDepartements = useCallback(async () => {
Tous ces calculs doivent se faire côté serveur.

2022-04-04 10:56 UTC, tmerlier commented on components/bases-locales/charte/search-partners-results.js
> +          </div>
Ce message pourrait s'afficher même des résultats s'affiche. Exemple : `Vous souhaitez être référencé comme Partenaire de la Charte de la Base Adresse Nationale, contactez nous.`

2022-04-04 10:56 UTC, tmerlier commented on pages/bases-locales/charte/communes.js
> +  const orderedRegions = [...regions].sort((a, b) => a.nom.localeCompare(b.nom))
Classement à faire côté serveur.

2022-04-04 10:56 UTC, tmerlier commented on pages/bases-locales/charte/communes.js
> +          {orderedRegions.map(region => <Region key={region.code} {...region} communes={partners.communes} />)}
Il faut filtrer afin que seuls les communes appartenant à la région soient envoyées.

2022-04-06 10:01 UTC, GllmR approved these changes

2022-04-07 09:24 UTC, tmerlier approved these changes

2022-04-07 09:30 UTC, merged