Résolution problème affichage adresse des COM
BaseAdresseNationale/adresse.data.gouv.fr pull request #1168
Opened 2022-05-18 15:03 UTC by Maxine-Le-Pennec

Cette PR propose un fix à l'issue #1163

**Les problèmes** : 

- L'accès à la page `/commune/<codecommune>` d'une commune des COM mène à une erreur `500`.
- Une erreur d'affichage de l'adresse se produit également sur l'explorateur.

Ces erreurs sont dûes à certaines informations manquantes chez les COM (infos de la mairie, nom/code region/departement) qui mènent soit à une erreur au chargement de la page faute d'existence des données, soit à un souci d'affichage.

**Résolution** :

- Retourner `null` si les informations ne sont pas présentes dans un `getInitialProps` afin d'éviter l'erreur `500` au retour des props.
- Conditionner l'affichage à la présence ou non de certaines clés/valeurs

### **AVANT**
### Page `/commune/97501`
<img width="632" alt="168839070-34771d16-b2f8-4eed-83e1-f3bb0ef4019c" src="https://user-images.githubusercontent.com/66621960/169072725-d6fc74f1-5752-4392-b76b-95d9150d4d46.png">

### Explorateur
<img width="705" alt="168838961-30c17213-e688-4848-ac45-71d6ddfb64e7" src="https://user-images.githubusercontent.com/66621960/169072937-8ee0f66b-36ea-47c5-9301-9fb7da8df25f.png">

### **APRÈS**
<img width="1440" alt="Capture d’écran 2022-05-18 à 17 01 24" src="https://user-images.githubusercontent.com/66621960/169073456-e4c44183-b887-448f-9403-04434d8e72e0.png">
<img width="707" alt="Capture d’écran 2022-05-18 à 17 01 55" src="https://user-images.githubusercontent.com/66621960/169073567-11d1ef86-2e4d-4048-8305-d24954538fcd.png">

Close #1163

2022-05-18 17:02 UTC, IGNFBourcier reviewed
Pour les infos mairies, on peut les récupérer avec le type mairie_com
`${API_ETABLISSEMENTS_PUBLIC}/communes/${codeCommune}/${type}`

2022-05-19 09:15 UTC, Maxine-Le-Pennec commented
> Pour les infos mairies, on peut les récupérer avec le type mairie_com `${API_ETABLISSEMENTS_PUBLIC}/communes/${codeCommune}/${type}`

Ça retourne le même objet, le résultat est le même :)

2022-05-19 11:46 UTC, jdesboeufs requested changes

2022-05-19 12:25 UTC, Maxine-Le-Pennec commented on components/base-adresse-nationale/explorer.js
> +  const isCOM = address.commune ? (
Non j'avoue j'ai pas checké à la main haha !
Je change ça pour éviter les dommages collatéraux :)

2022-05-19 13:01 UTC, jdesboeufs commented on components/base-adresse-nationale/explorer.js
> +  const isCOM = address.commune ? (
J'ai vérifié, il n'y en a pas ;)
Mais autant se protéger dans le cas où on aurait une réforme des territoires avant que l'API Géo ne soit adaptée.

2022-05-19 13:03 UTC, Maxine-Le-Pennec commented on components/base-adresse-nationale/explorer.js
> +  const isCOM = address.commune ? (
Comment tu as fait pour vérifier aussi vite ? :')

2022-05-20 12:14 UTC, GllmR commented on components/base-adresse-nationale/numero/index.js
> -Numero.defaultProps = {
Je ne comprends pas, tu as enlevé les `defaultProps`, mais tu ne les as pas remises alors qu'elles ne sont pas `required` ?

2022-05-24 08:00 UTC, tmerlier commented on components/base-adresse-nationale/region-infos.js
> +    return `${region.nom} - ${departement.nom} (${departement.code})`
Les `propTypes` indique que `departement` et `region` doivent être des `string`.

2022-05-24 08:02 UTC, tmerlier commented on components/base-adresse-nationale/numero/index.js
> +          <RegionInfos codeCommune={commune.code} region={commune.region} departement={commune.departement} />
Les props `region` et `commune` sont utilisées comme des objets dans `<RegionInfos />`

2022-05-24 08:03 UTC, tmerlier commented on components/base-adresse-nationale/voie/numero.js
> +
Pourquoi cette modification ? Et pourquoi dans cette PR ?

2022-05-24 09:45 UTC, IGNFBourcier commented
> > Pour les infos mairies, on peut les récupérer avec le type mairie_com `${API_ETABLISSEMENTS_PUBLIC}/communes/${codeCommune}/${type}`
> 
> Ça retourne le même objet, le résultat est le même :)

Dans le cas exemple, on  récupère l'info pour le bouton contact:
https://etablissements-publics.api.gouv.fr/v3/communes/97501/mairie_com
https://etablissements-publics.api.gouv.fr/v3/communes/97501/mairie
donc combiné avec isCOM ca devrait atténuer les cas de désactivation

2022-05-24 19:58 UTC, jdesboeufs commented on lib/api-etablissements-public.js
> +export function getMairie(codeCommune, type) {
La logique voudrait qu'on évalue le type dans la fonction et pas en dehors.

2022-05-24 19:58 UTC, jdesboeufs approved these changes

2022-05-30 09:16 UTC, tmerlier approved these changes

2022-05-30 09:18 UTC, merged