Accessibilité non-visuelle des liens et éléments interactifs
BaseAdresseNationale/adresse.data.gouv.fr pull request #1207
Opened 2022-06-22 10:40 UTC by Maxine-Le-Pennec

Cette PR fait suite à [**Modification du wording des liens et boutons par soucis d'accessibilité**](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/pull/1197).

Elle se concentre sur 

- l'ajout d'attributs tels que `aria-label` pour outrepasser l'`innerText` par les lecteurs d'écran et rajouter du contexte à l'action.

- L'ajout de l'attribut `passHref` aux composants `Link` de Nextjs, parents de balises `<a>` (joue sur l'accessibilité et le SEO)

- L'ajout de rôles et types pertinents à des éléments interactifs afin de faciliter leur compréhension par les utilisateurs du lecteur d'écran

2022-06-24 14:40 UTC, GllmR requested changes
Par rapport au `passhref`, d’après moi, il n’est pas nécessaire de l’ajouter lorsque l’enfant direct est une balise `<a>`, comme indiqué dans la [documentation](https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-custom-component-that-wraps-an-a-tag).

On peux d’ailleurs constater qu’après la compilation, la balise `<Link />` est bien transformée en balise `<a>` contenant le `href`.

2022-06-24 14:40 UTC, GllmR commented on components/maplibre/select-paint-layer.js
> +          aria-label='Séléctionner le layer'
"Sélectionner l’origine des adresses" ?
"Modifier l’affichage des adresses sur la carte" ?

2022-06-24 14:40 UTC, GllmR commented on components/maplibre/switch-map-style.js
> +          aria-label={isVector ? 'Passer en vue satellite' : 'Passer en vue vectoriel'}
Il a un problème avec le style ici : 
Avant : 

![image](https://user-images.githubusercontent.com/56537238/175557398-c9567c36-b467-4d7b-9fce-5db1d8b3a027.png)

Après : 

![image](https://user-images.githubusercontent.com/56537238/175557471-39b8dfab-de47-4b6e-816a-bfe73cb0905b.png)

2022-06-28 10:26 UTC, GllmR approved these changes

2022-06-29 09:38 UTC, Maxine-Le-Pennec commented on components/maplibre/select-paint-layer.js
> +          aria-label='Séléctionner le layer'
Oui c'est mieux ça

2022-06-29 10:02 UTC, tmerlier commented on components/evenement/event-banner.js
> +  const accessibleDate = selectedEvent && new Date(selectedEvent.date).toLocaleDateString('fr-FR', options)
Celles-ci également, `utils/date.js`

2022-06-29 10:08 UTC, tmerlier commented on components/fantoir/body-list-fantoir.js
> +      <button type='button' aria-label={`Accéder aux données de ${contents[0]}`} onClick={onSelect}>
Pourquoi uniquement prendre le premier index ?

2022-06-29 10:12 UTC, tmerlier commented on components/map-bal-section.js
> +        </div>
Le lien disparait complètement ? Comment rejoint-on la page `/deploiement-bal` ?

2022-06-29 10:15 UTC, tmerlier commented on components/maplibre/switch-map-style.js
> +          aria-label={isVector ? 'Passer en vue satellite' : 'Passer en vue vectoriel'}
Il y a essentiellement de la vue aérienne il me semble. Le bon terme serait "orthophoto", mais certainement un peu trop technique ?

2022-06-29 10:18 UTC, tmerlier commented on components/question.js
> +          aria-label={`Nous contacter pour la raison suivante : ${question}`}
Pourquoi "nous contacter" ? Ça serait plutôt `Voir/Afficher la réponse à la question : …` non ?

2022-06-29 10:20 UTC, tmerlier commented on components/selectable-item-list.js
> +              aria-label={buttonIcon === '+' ? `Sélectionner ${item.value}` : `Désélectionner ${item.value}`}
Si on se base sur la valeur de `buttonIcon` alors il faut lister les valeurs autorisées dans le `PropTypes`.

2022-06-29 10:22 UTC, tmerlier commented on components/social-media.js
> +        <a href='https://twitter.com/adressedatagouv?lang=fr' aria-label='Visiter notre compte Twitter'>
Essayons d'être un maximum homogène sur les termes `consulter/visiter`. Choisissons-en un et utilisons-le partout où cela est nécessaire.

2022-06-29 10:27 UTC, tmerlier commented on components/table-list/table/body.js
> +          aria-label={`Accéder à la commune ${item.nom} dans l’explorateur`}
Ce composant est "neutre" et est conçu pour permettre l’affichage de toute sorte de liste et non pas uniquement des communes. Il est donc préférable de passer en `props` une méthode permettant de créer ce `aria-label`.

Pour ce qui est du label en lui-même, le nom "explorateur" n'est pas public, c'est le petit nom que nous lui avons donné.
Quelque chose comme "Consulter les adresses de la commune de xxx dans la Base Adresse Nationale" serait plus adapté.

2022-06-29 10:28 UTC, tmerlier commented on components/table-list/table/head.js
> +    style={{display: 'inline-flex', border: 'none', background: 'none', color: 'white'}}
Évitons le `style in-line` quand cela est possible, c'est une pratique assez dépréciée.

2022-06-29 10:31 UTC, tmerlier commented on components/table-list/table/head.js
> +const order = (a, b, direction) => (
```suggestion
const order = (a, b, order) => (
```

2022-06-29 10:33 UTC, tmerlier commented on components/table-list/table/head.js
> +const order = (a, b, direction) => (
Je suis étonné que le linter ne dise rien sur le fait qu'on utilise `order` et non `Order` pour le nom du composant…

2022-06-29 11:52 UTC, Maxine-Le-Pennec commented on components/bases-locales/bases-adresse-locales/summary.js
> +              <a href={url} aria-label={`Télécharger les ${title}`}>
Oui pour rajouter du contexte à l'utilisateur qui utilise le lecteur d'écran. C'est bien qu'il puisse savoir instantanément quelles adresses il télécharge. Ça peut vite devenir le bazar quand tu as 5 boutons qui disent tous "Télécharger la Base Adresse Locale" alors que tu peux facilement avoir "Télécharger les Adresses de xxxx". 
Visuellement ce n'est pas un problème pour cerner le contexte avec juste "Télécharger la Base Adresse Locale"

2022-06-29 12:02 UTC, tmerlier commented on components/bases-locales/bases-adresse-locales/summary.js
> +              <a href={url} aria-label={`Télécharger les ${title}`}>
Ok, mais dans ce cas `title` c'est `adresses de xxx` ?

2022-06-29 12:56 UTC, Maxine-Le-Pennec commented on components/map-bal-section.js
> +        </div>
Il y a un bouton juste en dessous qui redirige déjà vers `/deploiement-bal`

2022-06-30 08:31 UTC, Maxine-Le-Pennec commented on components/fantoir/body-list-fantoir.js
> +      <button type='button' aria-label={`Accéder aux données de ${contents[0]}`} onClick={onSelect}>
Parce que le second c'est juste le code département

2022-07-04 11:50 UTC, Maxine-Le-Pennec commented on components/bases-locales/bases-adresse-locales/summary.js
> +              <a href={url} aria-label={`Télécharger les ${title}`}>
Oui c'est tout à fait ça. 
Tu préfères : `"Télécharger la Base Adresse Local de commune X"` ?

2022-07-04 13:01 UTC, tmerlier commented on components/bases-locales/bases-adresse-locales/summary.js
> +              <a href={url} aria-label={`Télécharger les ${title}`}>
Non, c'est juste que ça me paraissait étrange que `title` contienne `adresses de xxx` mais si c'est ça alors ça me va.

2022-07-04 13:21 UTC, tmerlier approved these changes

2022-07-04 13:22 UTC, merged