Correction erreur 500 contact mairie
BaseAdresseNationale/adresse.data.gouv.fr pull request #1224
Opened 2022-07-04 15:22 UTC by Maxine-Le-Pennec

Corrige l'erreur 500 sur la page commune, occasionnée à l'ouverture de la modale contenant les infos de la mairie lorsque la `clef/valeur` email n'existe pas.

https://user-images.githubusercontent.com/66621960/177182966-1312fe01-86cf-4489-bc0f-43fdf07fc944.mp4

2022-07-05 08:28 UTC, GllmR requested changes

2022-07-05 08:28 UTC, GllmR commented on components/mairie/mairie-contact.js
> +  console.log(email)
🤗

2022-07-05 08:28 UTC, GllmR commented on components/mairie/mairie-contact.js
> +          font-size: ${email && email.length > 35 ? '14px' : '16px'};
Je ne suis pas sûr de comprendre, en quoi changer la taille du texte empêche une erreur 500 ? 
🤔

2022-07-05 09:34 UTC, Maxine-Le-Pennec commented on components/mairie/mairie-contact.js
> +  console.log(email)
oupsi

2022-07-06 13:51 UTC, cedric-famibelle-pronzola requested changes

2022-07-06 13:51 UTC, cedric-famibelle-pronzola commented on components/mairie/mairie-contact.js
> +          font-size: ${email && email.length > 35 ? '14px' : '16px'};
```suggestion
          font-size: ${email?.length > 35 ? '14px' : '16px'};
```

2022-07-06 14:19 UTC, cedric-famibelle-pronzola approved these changes

2022-07-06 15:00 UTC, merged