Affichage des noms de voie alternatifs
BaseAdresseNationale/adresse.data.gouv.fr pull request #1235
Opened 2022-07-13 09:35 UTC by Maxine-Le-Pennec

Les noms alternatifs des voies et des toponymes sont à présent affichés dans la liste des voies/toponymes, mais aussi dans l'en-tête de leurs pages.

Le premier nom alternatif figure sous le nom principal avec une police d’écriture plus petite et en italique.
Si plus de deux noms alternatifs existent, alors la mention `Afficher les alternatives régionales` apparait sous le nom principal avec une police d’écriture plus petite et en italique. Le survole de ce texte fait apparaitre un `tooltip` qui liste tous les noms alternatifs.

### **Liste de voies et toponymes**
<img width="673" alt="Capture d’écran 2022-07-13 à 10 56 48" src="https://user-images.githubusercontent.com/66621960/178701499-b1b9c471-9eef-463a-8ba1-d0d0f0fe655f.png">
<img width="650" alt="Capture d’écran 2022-07-13 à 10 57 27" src="https://user-images.githubusercontent.com/66621960/178701510-88ab1d09-761e-4219-98be-ec9f4bc8e27e.png">
<img width="668" alt="Capture d’écran 2022-07-13 à 10 59 01" src="https://user-images.githubusercontent.com/66621960/178701516-b42a007a-25d5-4820-b123-3f71790ee7b9.png">
<img width="664" alt="Capture d’écran 2022-07-13 à 10 59 18" src="https://user-images.githubusercontent.com/66621960/178701521-1247d73f-3c61-4c2c-9793-30cc55b33f1c.png">

----------------

### **Nom(s) alternatif(s) sur la section `voie`**
<img width="650" alt="Capture d’écran 2022-07-13 à 11 05 39" src="https://user-images.githubusercontent.com/66621960/178701804-207f0b4f-1f29-4edc-a20d-bd9481678e20.png">
<img width="667" alt="Capture d’écran 2022-07-13 à 11 05 58" src="https://user-images.githubusercontent.com/66621960/178701814-cbd7cf1b-8da5-4a4e-8496-8e1b65f9e4df.png">

----------------

### **Nom(s) alternatif(s) sur la section `numéros`**
<img width="651" alt="Capture d’écran 2022-07-13 à 11 07 53" src="https://user-images.githubusercontent.com/66621960/178701891-5ef8943e-b64b-407b-888b-56455a88ee96.png">
<img width="648" alt="Capture d’écran 2022-07-13 à 11 08 42" src="https://user-images.githubusercontent.com/66621960/178701899-a36376e5-f0d0-4339-8fcb-7080660f55d1.png">

2022-07-18 20:35 UTC, tmerlier requested changes
Attention, un certain nombre de modifications ne sont pas en rapport avec le support des langues régionales, mais sont plutôt des corrections du style. 
Elles sont bonnes, mais il est important de pas inclure de genre de corrections à l'avenir quand elles n'impactent pas directement les modifications de la PR. 

Cela gêne la lecture de la revue de code et potentiellement ralenti le déploiement de la PR si jamais ces correctifs ne sont pas bons.

2022-07-18 20:35 UTC, tmerlier commented on components/base-adresse-nationale/languages-preview.js
> +              </ul>
```suggestion
        <ul>
          {Object.values(nomAlt).map(voieName => (
            <li color='white' key={voieName}>{voieName}</li>
          ))}
        </ul>
```

2022-07-18 20:35 UTC, tmerlier commented on components/base-adresse-nationale/languages-preview.js
> +        <div className='alt-name'>{nomAlt[Object.keys(nomAlt)]}</div>
`Object.keys(nomAlt)` est calculé plusieurs fois, autant le calculé une fois et le stocker dans une variable.

2022-07-18 20:35 UTC, tmerlier commented on components/base-adresse-nationale/tooltip.js
> +      .tooltip-bottom .tooltip-text, .tooltip-left .tooltip-text, .tooltip-right .tooltip-text {
Toutes les modifications de style de ce fichier sont-elles compatibles avec les besoins des composants qui l'utilisaient ?

2022-07-19 10:56 UTC, Maxine-Le-Pennec commented on components/base-adresse-nationale/tooltip.js
> +      .tooltip-bottom .tooltip-text, .tooltip-left .tooltip-text, .tooltip-right .tooltip-text {
Oui, c'est bon normalement.

2022-07-19 14:17 UTC, Maxine-Le-Pennec commented on components/base-adresse-nationale/tooltip.js
> +      .tooltip-bottom .tooltip-text, .tooltip-left .tooltip-text, .tooltip-right .tooltip-text {
Un moyen prudent de dire que oui, j'ai vérifié hahaha

2022-07-19 15:23 UTC, Maxine-Le-Pennec commented
> Il faudrait ajouter les noms alternatifs dans la popup de la carte également.
> 
> ![Capture d’écran 2022-07-19 à 16 03 26](https://user-images.githubusercontent.com/7040549/179769717-8e48eba4-dfc4-4f1b-b436-b77ef1ae8256.png)

Résolu dans le commit [dceaf76](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/pull/1235/commits/dceaf768e246f65ab692e7e9dcdbf52bf331e5b7)

![Capture d’écran 2022-07-19 à 17 22 12](https://user-images.githubusercontent.com/66621960/179788044-2b0a00a5-bdfe-4a8e-9e99-f44040042706.png)
![Capture d’écran 2022-07-19 à 17 21 43](https://user-images.githubusercontent.com/66621960/179788051-57ffcc04-bafb-43f6-a856-4c3bb6a08b67.png)

2022-07-21 08:52 UTC, GllmR approved these changes

2022-07-21 13:12 UTC, tmerlier approved these changes

2022-07-21 13:14 UTC, tmerlier commented
> > Il faudrait ajouter les noms alternatifs dans la popup de la carte également.
> > ![Capture d’écran 2022-07-19 à 16 03 26](https://user-images.githubusercontent.com/7040549/179769717-8e48eba4-dfc4-4f1b-b436-b77ef1ae8256.png)
> 
> Résolu dans le commit [dceaf76](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/pull/1235/commits/dceaf768e246f65ab692e7e9dcdbf52bf331e5b7)
> 
> ![Capture d’écran 2022-07-19 à 17 22 12](https://user-images.githubusercontent.com/66621960/179788044-2b0a00a5-bdfe-4a8e-9e99-f44040042706.png) ![Capture d’écran 2022-07-19 à 17 21 43](https://user-images.githubusercontent.com/66621960/179788051-57ffcc04-bafb-43f6-a856-4c3bb6a08b67.png)

Fonctionnalité retirée de la PR, car les données ne sont pas disponibles dans le fond carto.

2022-07-21 14:50 UTC, merged