Remplacement des <button> par un composant réutilisable
BaseAdresseNationale/adresse.data.gouv.fr pull request #1269
Opened 2022-08-11 16:01 UTC by Maxine-Le-Pennec

Certains éléments intéractifs nécessitant un type `<button>` ne permettaient pas l'utilisation du composant <Button/> car le template data.gouv ne répond pas aux besoins en terme de design.

Ces éléments sont des boutons au design "neutre", c'est à dire sans bordure ou background et sont principalement utilisés au lieu d'une simple `<div>` pour des soucis d'accessibilité avec le lecteur d'écran.

Cette PR comprend : 

- La création d'un composant réutilisable afin d'éviter la répétition de style de ces boutons tout en gardant les impératifs d'accessibilité obligatoires (`aria-label` en props requise par exemple).

- Le remplacement de tous les `<button>` par le nouveau composant réutilisable.

Close #1222

2022-08-12 12:29 UTC, tmerlier approved these changes

2022-08-12 13:53 UTC, GllmR requested changes

2022-08-12 13:53 UTC, GllmR commented on components/evenement/event-banner.js
> +              <ActionButtonNeutral label={`Afficher l’évènement ${event.title}`} onClick={() => setSelectedEvent(event)}>
Il manque `{event.title}` de la ligne 52

2022-08-12 13:53 UTC, GllmR commented on components/mairie/mairie-schedules.js
> +          Horaires d’ouverture
Le chevron n’est plus du même côté, est-ce que c'est voulu ?

2022-08-17 12:45 UTC, GllmR approved these changes

2022-08-17 12:45 UTC, merged