Utilisation d'un composant réutilisable "carte d'identité de la commune"
BaseAdresseNationale/adresse.data.gouv.fr pull request #1271
Opened 2022-08-22 16:24 UTC by Maxine-Le-Pennec

Le but de cette PR est d'unifier le design des informations autour de la commune à l'aide d'un composant pouvant être utilisé à différents endroits.

Ici le composant existe déjà sur la [page commune](https://adresse.data.gouv.fr/commune/56078). L'idée est de réutiliser ce design dans l'explorateur à l'aide d'un composant unique.

### **AVANT**
<img width="474" alt="Capture d’écran 2022-08-22 à 18 21 35" src="https://user-images.githubusercontent.com/66621960/185970322-77ddc05c-86ce-4e6b-b72f-ed54946fa31e.png">

### **APRÈS**
<img width="473" alt="Capture d’écran 2022-08-22 à 18 12 11" src="https://user-images.githubusercontent.com/66621960/185969653-53057b96-0cbc-4c29-a9f1-90b589bfa4b8.png">
<img width="517" alt="Capture d’écran 2022-08-22 à 18 16 32" src="https://user-images.githubusercontent.com/66621960/185969639-acbc145f-a33a-4822-b2d1-4f77c19e841d.png">

<img width="1440" alt="Capture d’écran 2022-08-22 à 18 14 56" src="https://user-images.githubusercontent.com/66621960/185969648-f57095a9-3c94-4c1b-9953-41bf0b60a742.png">
<img width="1440" alt="Capture d’écran 2022-08-22 à 18 13 38" src="https://user-images.githubusercontent.com/66621960/185969650-93f4169d-c055-4a5b-b1a0-5cb135fb6272.png">

2022-08-23 14:33 UTC, GllmR approved these changes

2022-08-24 08:45 UTC, tmerlier requested changes

2022-08-24 08:45 UTC, tmerlier commented on components/commune-id-card.js
> +        <div className='value'>{departement.nom} {departement.code}</div>
```suggestion
        <div className='value'>{departement.nom} ({departement.code})</div>
```

2022-08-24 13:37 UTC, tmerlier approved these changes

2022-08-24 14:03 UTC, merged