Amélioration de l'affichage des métrics
BaseAdresseNationale/adresse.data.gouv.fr pull request #1277
Opened 2022-08-24 15:16 UTC by Maxine-Le-Pennec

Dans le cadre de l'amélioration de l'affichage des données métriques grâce à des composants réutilisables, deux éléments ont été modifiés ou créés.

- Des cartes indiquant des données numériques
Déjà utilisées dans la page commune, mais ayant besoin d'être adaptée pour s'afficher également sur l'explorateur.
<img width="1330" alt="Capture d’écran 2022-08-24 à 17 12 27" src="https://user-images.githubusercontent.com/66621960/186455549-f7bad3f8-d58d-45ce-af25-59f51cf842a8.png">

- Une barre de progression
Cette barre servira dans un premier temps à indiquer le niveau d'avancement des certifications d'adresses sur l'explorateur.
Elle est accompagnée d'informations telles que le nombre d'adresses précises étant certifiées/non-certifiées.

----------------------------------------
<img width="461" alt="Capture d’écran 2022-08-24 à 17 06 41" src="https://user-images.githubusercontent.com/66621960/186455424-f7ffc4e7-f7af-4b6c-b149-372daaf6ef56.png">
<img width="459" alt="Capture d’écran 2022-08-24 à 17 06 52" src="https://user-images.githubusercontent.com/66621960/186455433-16bbe03f-6f68-4994-9629-269c8bad432f.png">
<img width="458" alt="Capture d’écran 2022-08-24 à 17 15 28" src="https://user-images.githubusercontent.com/66621960/186456338-0277265c-c803-4558-abac-ae2c788af1db.png">

2022-08-25 09:52 UTC, GllmR requested changes
Il y a un petit souci avec les couleurs apparemment : 

![image](https://user-images.githubusercontent.com/56537238/186634112-0e386e35-b90b-4cb9-a2af-bc606c756d5b.png)

2022-08-25 10:06 UTC, tmerlier commented
Les métriques sous la barre de progression ne semblent pas très pertinentes dans le cas où toutes les adresses sont certifiées ou non.

Nous pourrions juste afficher `x adresses non certifiées` pour 0% de certification ou `x adresses certifiées` pour 100%

2022-08-25 12:10 UTC, tmerlier commented
L'affichage mobile subit un peu le manque de contrainte.
![Capture d’écran 2022-08-25 à 14 10 15](https://user-images.githubusercontent.com/7040549/186660678-d194dea8-88f3-4770-8972-72960abb12a5.png)

2022-08-25 12:28 UTC, tmerlier requested changes

2022-08-25 12:28 UTC, tmerlier commented on components/number-card.js
> +function NumberCard({label, number, color, size}) {
Un composant identique existe déjà `<Counter />`. Il n'est actuellement plus utilisé, je te propose de le remplacer par celui-ci dont le nom n'est pas très pertinent. 

`<Counter />` gère plus de chose, il lui manque juste un peu coup de CSS.

2022-08-25 12:28 UTC, tmerlier commented on components/number-card.js
> +        }
On pourrait simplifier en isolant le cas particulier comme ceci :
```suggestion
        .number-card div {
          font-size: ${size === 'regular' ? 'x-large' : 'medium'};
        }
        
        .number-card div:first-child {
          color: ${theme.primary};
        }
```

Le mieux étant tout de même de donner une classe spécifique à cette première `div`. Les `:first` et `:last` servent surtout quand il n'y a pas d'autre moyen d'atteindre le `div` autrement.

2022-08-25 12:28 UTC, tmerlier commented on components/number-card.js
> +        }
Il y a beaucoup de variable qui influencent le style dans ce composant et on a tendance à trop se laisser influencer par React pour gérer ce genre de cas.
Pourtant, il serait plus "style friendly" de définir plusieurs classes et de les attribuer en fonction des variables.

Il n'est pas nécessaire d'intervenir ici, c'est plus une remarque pour ne pas oublier les bonnes pratiques.

2022-08-25 12:28 UTC, tmerlier commented on components/base-adresse-nationale/commune/details.js
> +  nbNumerosCertifies
Ça commence à faire pas mal de `props`. Nous pourrions les grouper par utilité pour alléger un peu visuellement.

On peut déjà séparer les stats (nbVoies, nbLieuxDits, etc.) des infos du territoires (region, departement, codePostaux, etc)

2022-08-25 12:28 UTC, tmerlier commented on components/base-adresse-nationale/commune/index.js
> +          <Image src='/images/icons/commune.svg' height={50} width={50} />
Je pense que nous allons devoir prévoir de quoi adapter la taille de l'image, au moins pour le mobile.

2022-08-25 15:26 UTC, Maxine-Le-Pennec commented on components/base-adresse-nationale/commune/index.js
> +          <Image src='/images/icons/commune.svg' height={50} width={50} />
Je pensais utiliser `flex-wrap` mais je ne vois pas comment centrer l'image au moment du wrap sans utiliser de media-q

2022-08-26 08:10 UTC, Maxine-Le-Pennec commented
> Les métriques sous la barre de progression ne semblent pas très pertinentes dans le cas où toutes les adresses sont certifiées ou non.
> 
> Nous pourrions juste afficher `x adresses non certifiées` pour 0% de certification ou `x adresses certifiées` pour 100%

Je pense que ça va être un peu redondant avec l'icône de certification survolable à côté de la barre de progression. Autant ne rien mettre non ?

J'ai testé et je trouve que ça fait un peu trop de répétition : 
<img width="455" alt="Capture d’écran 2022-08-26 à 10 10 08" src="https://user-images.githubusercontent.com/66621960/186854969-ff8584bf-78fa-43da-8308-7b45b1c4ded2.png">

2022-08-30 08:21 UTC, tmerlier commented
> 

Non, car on a le nombre d'adresses de la commune.

2022-08-30 15:18 UTC, Maxine-Le-Pennec commented
> > 
> 
> Non, car on a le nombre d'adresses de la commune.

Résolu via le commit [e7bec1b](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/pull/1277/commits/e7bec1b6d62730b58d46076387d141e365a2c7ab)

2022-08-31 09:48 UTC, Maxine-Le-Pennec commented on components/base-adresse-nationale/commune/index.js
> +          <Image src='/images/icons/commune.svg' height={50} width={50} />
Corrigé via le commit [7e5faf2](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/pull/1277/commits/7e5faf27e7c4903728ccfb3f66528d551ff374a5)

2022-08-31 13:18 UTC, Maxine-Le-Pennec commented
> On manque un peu de `padding` ![Capture d’écran 2022-08-31 à 11 51 44](https://user-images.githubusercontent.com/7040549/187651452-9930da90-9d24-4294-923b-d7f9d06eaeae.png)

Résolu via le commit https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/pull/1277#issuecomment-1232722576

2022-10-14 09:25 UTC, tmerlier approved these changes

2022-12-14 12:16 UTC, mmortier commented
Je ne vois pas beaucoup de différence avec l'original : 
![PR](https://user-images.githubusercontent.com/7045982/207592832-5570800a-0c23-4020-a046-3539ddf915d3.png)
A gauche le résultat en local sur cette branche et à droite l'original.
Ets-ce que ça vaut le coup? Je trouve qu'on comprend moins bien le terme "répertorié"

2022-12-14 13:11 UTC, mmortier commented
Ok là sur la carte BAN il y a du changement. Mais comme il y a eu des modifications qui ont été au final supprimées c'était un peu dur à suivre..

2022-12-14 13:58 UTC, mmortier requested changes

2022-12-14 13:58 UTC, mmortier commented on components/commune/commune-infos.js
> +            <Counter label={nbVoies <= 1 ? 'Voie répertoriée' : 'Voies répertoriées'} value={nbVoies} />
Je laisserai "Voie" et "Voies" pour être raccord avec les termes qu'on utilise dans la carte BAN. J'enlèverai le terme "répertoriée(s)" que je ne trouve pas clair.

2022-12-14 13:58 UTC, mmortier commented on components/commune/commune-infos.js
> +            <Counter label={nbLieuxDits <= 1 ? 'Lieu-dit répertorié' : 'Lieux-dits répertoriés'} value={nbLieuxDits} />
idem ci dessus enlever "répertorié"

2022-12-14 13:58 UTC, mmortier commented on components/commune/commune-infos.js
> +            <Counter label={nbNumeros <= 1 ? 'Numéro répertorié' : 'Numéros répertoriés'} value={nbNumeros} />
idem

2024-12-11 13:19 UTC, vinsag commented
Cette PR est devenu inutile avec la refonte

2024-12-11 13:19 UTC, closed without merging