Add new Button to contribute page
BaseAdresseNationale/adresse.data.gouv.fr pull request #1356
Opened 2022-11-29 16:24 UTC by FLoreauIGN

#1342
Besoin : mettre sur le site adresse l'accès à la plateforme osmose d'animation du collectif des usagers de la BAN.
Solution : ajout d'un bouton permettant d'y accéder sur la page contribuer.
Ajout sur la page contribuer :
![image](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/assets/116554403/c0af3c5e-2a3d-44ea-b69d-1b5505832c02)

2022-11-30 07:46 UTC, vinsag approved these changes

2022-11-30 09:22 UTC, FrederiqWilliams reviewed
il manque un "s" à la fin de "services associé". 
Ensuite c'est bon.

2022-11-30 09:29 UTC, tmerlier requested changes

2022-11-30 09:29 UTC, tmerlier commented on pages/contribuer.js
> +          <ButtonLink href='https://analytics-eu.clickdimensions.com/ignfr-agj1s/pages/pat1ve7fee27owanot90mw.html?PageId=bcf5a4a5c54eed11bba3000d3adf7433' isExternal>
Ce bouton est un tracker… 

Depuis sa création, ce site évite de polluer l'utilisateur avec ce genre de chose ;)

2022-11-30 09:41 UTC, FrederiqWilliams reviewed
Voilà le lien direct sur la page du formulaire d'inscription : 
https://www.ign.fr/professionnels/rejoignez-la-communaute-dutilisateurs-de-la-ban

2022-12-02 16:24 UTC, FrederiqWilliams commented on pages/contribuer.js
> +          <ButtonLink href='https://analytics-eu.clickdimensions.com/ignfr-agj1s/pages/pat1ve7fee27owanot90mw.html?PageId=bcf5a4a5c54eed11bba3000d3adf7433' isExternal>
Je vais fournir un lien direct sur une page d'inscription qui sera sur le site de l'IGN

2022-12-12 10:06 UTC, tmerlier requested changes

2022-12-12 10:06 UTC, tmerlier commented on pages/contribuer.js
> +          <ButtonLink href='https://www.ign.fr/professionnels/rejoignez-la-communaute-dutilisateurs-de-la-ban' isExternal>
Attention, la page sur laquelle se trouve le formulaire ne prévient pas non plus de la présence sur tracker.
D'ailleurs ce genre de contenu peut être bloqué et les utilisateurs peuvent se retrouver devant un page vierge.

2022-12-14 13:38 UTC, jdesboeufs requested changes
Tracker toujours présent mais camouflé sur le site ign.fr.
Il s'agit d'un site en data.gouv.fr il n'est pas possible de faire ça.

2022-12-14 14:35 UTC, vdct commented on pages/contribuer.js
> +          <ButtonLink href='https://www.ign.fr/professionnels/rejoignez-la-communaute-dutilisateurs-de-la-ban' isExternal>
> les utilisateurs peuvent se retrouver devant un page vierge

Je confirme, ça vient de m'arriver cf https://twitter.com/_vdct/status/1602338457464061953 et suivants

2023-01-26 11:13 UTC, nkokla commented
Je reprends un peu conversation. 
Il s'agit du site IGN. Il faudrait leur remonter l'info mais ça sort du cadre de la BAN.
Sinon, pour te répondre @FrederiqWilliams, la mention RGPD n'est pas suffisante. Il faut un accord explicite (donc, par une action de l'internaute) avant de pouvoir déposer des cookies ou  identifiant de tracking qui sont partagé et utilisé hors d'une nécessité technique (les cookies Légitimes pour usage interne uniquement et non partagé vers une infrastructures autre que celle de l'IGN).
Généralement, ça se traduit tout simplement par une petite fenêtre d'acceptation de cookie.

2023-07-12 08:57 UTC, mmortier approved these changes

2023-07-12 08:57 UTC, merged