Feat/add re users
BaseAdresseNationale/adresse.data.gouv.fr pull request #1384
Opened 2022-12-22 13:54 UTC by FLoreauIGN

#1336 

Ajout de 6 ré-utilisateurs sur la page des ré-utilisateurs (Acceslibre, Gendarmerie nationale, HERE, IGN, SDIS64 et TomTom)
Ajout d'un texte décrivant l'usage de la BAN pour chaque ré-utilisateurs
Ajout d'un bouton permettant d'accéder au blog sur la page des ré-utilisateurs

Avant :
![image](https://user-images.githubusercontent.com/116554403/209148425-7d717afc-eccb-4c81-94cd-2720e38d3b98.png)

Après :
![image](https://user-images.githubusercontent.com/116554403/209148756-74e191d9-e370-49d7-8825-1a0b448220c2.png)

Exemple d'affichage d'usages :
![image](https://user-images.githubusercontent.com/116554403/209148919-feb299f2-2c52-487c-9169-e3093521c040.png)

2022-12-30 15:26 UTC, olivierdelteil commented
peut on remplacer "afficher les informations" par "Quel usage de la BAN ?

2023-01-05 09:27 UTC, tmerlier requested changes
Je te propose de créer un nouveau composant dédié aux utilisateurs. Cela permettra d'être plus libre sur les données à afficher et comment les afficher.

Par extension, le `json` pourrait être adapté également, car il est aujourd'hui une copie de celui des partenaires.
Le `json` des partenaires n'a par ailleurs pas évolué lors de la séparation des partenaires, rendant des champs comme `isCompagny` obsolète. Un petit coup de propre serait le bienvenu à l'occasion.

2023-01-06 17:15 UTC, olivierdelteil commented on components/bases-locales/charte/partner.js
> +        )}
ok pour moi, si cela ne charge pas la page

2023-01-10 12:49 UTC, tmerlier commented on components/donnees-nationales/re-users.js
> +        {items.map(item => <ReUser key={item.name} reUserInfos={item} />)}
Tu pourrais déstructurer l'utilisateur pour utiliser les valeurs qui t'intéressent dans le composant.

```suggestion
        {items.map(user => <ReUser key={item.name} {...user} />)}
```

2023-01-10 13:22 UTC, tmerlier commented
Attention à ne pas `push force` pendant les revues, ce n'est pas une bonne pratique ;)

Si c'est nécessaire, il est toujours possible de "nettoyer" les commits en utilisant un `rebase`.

2023-01-23 15:40 UTC, tmerlier requested changes

2023-01-23 15:40 UTC, tmerlier commented on components/donnees-nationales/user-ban.js
> +  const {name, link, usage, picture, height, width} = {...UserInfos}
```suggestion
  const {name, link, usage, picture, height, width} = UserInfos
```

2023-01-25 15:34 UTC, mmortier approved these changes

2023-01-25 15:39 UTC, vinsag approved these changes

2023-01-25 15:41 UTC, tmerlier approved these changes
Le `style jsx` du composant `<UserBAN />` a pas mal de choses qui n'ont pas besoin d'être là. Il faudrait faire une petite passe de nettoyage à l'occasion.

2023-01-25 15:43 UTC, merged

2023-01-25 15:45 UTC, nkokla commented
> Le `style jsx` du composant `<UserBAN />` a pas mal de choses qui n'ont pas besoin d'être là. Il faudrait faire une petite passe de nettoyage à l'occasion.

Yes. Ce sera surement révisé lors du passage au DSFR.