Documentation validateur
BaseAdresseNationale/adresse.data.gouv.fr pull request #1570
Opened 2023-07-18 12:28 UTC by fufeck

## Context

Pour le moment il n'y a aucune documentation sur a quoi sert et comment fonctionne  le validateur.

## Fonctionnalité

Ajout d'une documentation sur la page validateur avec l'explication des profiles, et les différentes alerte et erreurs de chacun

2023-07-18 12:31 UTC, fufeck commented
je ne suis pas vraiment sur du wording et de l'endroit ou mettre cette page, n'hésitez surtout pas a me dire si un truc vous choc

2023-07-25 16:10 UTC, nkokla commented on components/bases-locales/validator/index.js
> +  }, [profile, file, getProfileReport])
Ce n'est pas hyper important, mais j'ai un doute sur cette ligne.
- `profile` n'est pas utilisé au sein du `useEffect` et ne devrait donc pas faire partie du tableau de dépendances.
- Ce que j'en comprends, c'est que c'est `getProfileReport` qui a une dependance sur `profile`et devrait donc etre inclu dans une ùseCallback` ? (Et d'ailleurs on devrait également trouver `report` parmis ces dependances).

Bref, peut-être a voir sur une prochaine PR. (Je me le note)

2023-07-27 14:29 UTC, mmortier requested changes
J'ai corrigé des fautes d'orthographes. Il faudrait peut être revoir le wording, je laisse @Ariane-Rose donner son avis

2023-07-27 14:29 UTC, mmortier commented on components/bases-locales/validator/validateur-documentation/index.js
> +        <p>Le validateur Bal est l&apos;outil qui permet de vérifier l&apos;intégrité des données d&apos;un fichier au format csv BAL pour la plateforme Bases Adresses Nationnals</p>
```suggestion
        <p>Le validateur Bal est l&apos;outil qui permet de vérifier l&apos;intégrité des données d&apos;un fichier au format csv BAL pour la plateforme Base Adresse Nationale</p>
```

2023-07-27 14:29 UTC, mmortier commented on components/bases-locales/validator/validateur-documentation/index.js
> +        <p>Le validateur prend un fichier csv BAL en entré et retourne si ce dernier est valide ou non</p>
```suggestion
        <p>Le validateur prend un fichier csv BAL en entrée et retourne si ce dernier est valide ou non</p>
```

2023-07-27 14:29 UTC, mmortier commented on components/bases-locales/validator/validateur-documentation/index.js
> +            <li><strong>Les alertes</strong> n&apos;empèchent pas le fichier Bal d&apos;être valide et sera donc accepté, mais ces dernières doivent être corriger pour une meilleur intégrité des donn
```suggestion
            <li><strong>Les alertes</strong> n&apos;empèchent pas le fichier Bal d&apos;être valide et sera donc accepté, mais ces dernières doivent être corrigées pour une meilleure intégrité des données</li>
```

2023-07-27 14:29 UTC, mmortier commented on components/bases-locales/validator/validateur-documentation/index.js
> +          Il existe deux profiles sur le validateur, qui sont plus ou moins tolérent sur les erreurs et alertes
```suggestion
          Il existe deux profils sur le validateur, qui sont plus ou moins tolérant sur les erreurs et alertes
```

2023-07-27 14:29 UTC, mmortier commented on components/bases-locales/validator/validateur-documentation/index.js
> +            <li><strong>BAL 1.3 Etalab</strong> est un profile exeptionel pour certaine communautés de communes, il est plus flexible</li>
```suggestion
            <li><strong>BAL 1.3 Etalab</strong> est un profil exceptionnel pour certaines communautés de communes, il est plus flexible</li>
```

2023-07-27 14:29 UTC, mmortier commented on components/bases-locales/validator/validateur-documentation/index.js
> +            <li><strong>BAL 1.3 Etalab Strict</strong> est le profile par defaut</li>
```suggestion
            <li><strong>BAL 1.3 Etalab Strict</strong> est le profil par défaut</li>
```

2023-07-27 14:29 UTC, mmortier commented on components/bases-locales/validator/validateur-documentation/index.js
> +            <li><strong>Les erreurs</strong> empèchent le fichier Bal d&apos;être valide et sera donc rejeter</li>
```suggestion
            <li><strong>Les erreurs</strong> entraînent un rejet du fichier BAL. Il sera considéré comme non valide</li>
```

2023-07-27 14:29 UTC, mmortier commented on components/bases-locales/validator/validateur-documentation/index.js
> +            <li><strong>Les alertes</strong> n&apos;empèchent pas le fichier Bal d&apos;être valide et sera donc accepté, mais ces dernières doivent être corriger pour une meilleur intégrité des donn
```suggestion
            <li><strong>Les alertes</strong> n&apos;empêchent pas le fichier Bal d&apos;être valide et sera donc accepté, mais ces dernières peuvent être corrigées pour une meilleure intégrité des données</li>
```

2023-08-01 11:31 UTC, fufeck commented on components/bases-locales/validator/index.js
> +  }, [profile, file, getProfileReport])
On est obligé de mettre profile dans les dépendance du useEffect, car c'est ce qui déclenche le recalcule des erreurs en fonction de la selection du profil. Ensuite pour les useCallback et cie, j'essaye de les utiliser avec parcimonie pour ne pas trop polluer le code quand il n'y a pas de gain de perf a la clé.

2023-08-01 15:27 UTC, MaGOs92 reviewed
Je trouve ça bizarre qu'il n'y ait pas de point à la fin des phrases dans le paragraphe "Documentation Validateur".

Sinon à la fin des rubriques, il y'a le titre "Alertes par colonne" qui ne comporte rien. Est-ce normal?

2023-08-02 06:14 UTC, fufeck commented
> Je trouve ça bizarre qu'il n'y ait pas de point à la fin des phrases dans le paragraphe "Documentation Validateur".
> 
> Sinon à la fin des rubriques, il y'a le titre "Alertes par colonne" qui ne comporte rien. Est-ce normal?

C'est plus un titre qu'une phrase et oui, je vais regarder ca, je mets le titre "Alertes par colonne" alors qu'il n'y a aucune alertes

2023-09-01 13:50 UTC, MaGOs92 approved these changes
LGTM, il faudra passer en prod la MAJ 2.16 avant pour avoir les bons noms de profils

2023-09-01 13:50 UTC, MaGOs92 commented on components/bases-locales/validator/validateur-documentation/index.js
> +            <li><strong>Les alertes</strong> n&apos;empêchent pas la publication et le fichier Bal sera donc accepté, mais ces dernières peuvent être corrigées pour une meilleure intégrité des donnée
Nit: Bal => BAL

2023-09-01 13:50 UTC, MaGOs92 commented on components/bases-locales/validator/validateur-documentation/profile-documentation.js
> +      <style jsx>{`
Autant mettre tout le CSS dans ton styled component

2023-09-04 13:34 UTC, merged