Fufeck refacto deployement bal
BaseAdresseNationale/adresse.data.gouv.fr pull request #1597
Opened 2023-09-06 13:49 UTC by fufeck

## Context

Le `/dashboard` sur mes-adresses a été fermé
Il faut migrer la partie déploiement des BAL sur la page `deploiement-bal`

2023-09-07 15:37 UTC, MaGOs92 requested changes

2023-09-07 15:37 UTC, MaGOs92 commented on components/bases-locales/deploiement-bal/commune-bal-list.js
> +  const title = `${codeCommune} ${nomCommune} - ${balsCommune.length > 0 ? balsCommune.length + 'BAL(s)' : 'Aucune BAL'} `
Il manque un espace entre balsCommune.length et 'BAL(s)'. D'ailleurs ça serait mieux de tout mettre en template string, c'est plus lisible je trouve

2023-09-07 15:37 UTC, MaGOs92 commented on components/bases-locales/deploiement-bal/bal-card.js
> +          <ButtonLink href={balUrl} style={{width: '100%'}} target='_blanck'>Consulté</ButtonLink>
Typos:
- blank
- Consulter

2023-09-07 15:37 UTC, MaGOs92 commented on components/bases-locales/deploiement-bal/panel-bal.js
> +          <h3>Status des BAL(s)</h3>
Typo : Statut

2023-09-07 15:37 UTC, MaGOs92 commented on components/bases-locales/deploiement-bal/bal-card.js
> +      <style jsx>{`
Maintenant tu peux utiliser styled-components pour le CSS

2023-09-07 15:37 UTC, MaGOs92 commented on components/bases-locales/deploiement-bal/bal-card.js
> +      'demo',
Il y'a pas un filtre sur les BAL en démo côté back?

2023-09-07 15:37 UTC, MaGOs92 commented on components/bases-locales/deploiement-bal/panel-bal.js
> +        bals?.filter(bal => bal.status === 'published')?.length || 10,
Pourquoi 10?

2023-09-07 15:37 UTC, MaGOs92 commented on server/deploiement.js
> +      // Const statsData = await fetchStatsData()
à supprimer

2023-09-08 09:54 UTC, fufeck commented on components/bases-locales/deploiement-bal/bal-card.js
> +      <style jsx>{`
Alors oui, pour les component du dsfr je trouve ca pratique, mais je trouve ca plus clair pour cette situation

2023-09-08 09:55 UTC, fufeck commented on components/bases-locales/deploiement-bal/bal-card.js
> +      'demo',
Sisi, j'ai copié coller les PropsTYpes sans regarder

2023-09-08 10:36 UTC, fufeck commented
> Tests : <img alt="Capture d’écran 2023-09-07 à 17 39 58" width="1427" src="https://user-images.githubusercontent.com/4552238/266369921-18415ff8-6948-4b4a-9e10-3d279e3fc4d2.png">
> 
> * Bouton de téléchargement : Il s'agit du fichier du dashboard "Déploiement BAL", je pense qu'il faut masquer le bouton.
> * Carte : J'ai sélectionné un EPCI mais tout le département d'indre et loire est "grisé", sur les communes de l'EPCI on a bien la pop-up mais pas sur les autres communes du département.
> * Carte : La pop-up est celle de déploiement BAL en mode Suivi Mes Adresses
> * Carte: Quand je switch de dashboard (Suivi Mes Adresses / Déploiement BAL), la carte reste identique.
> * Carte : Quand le dashboard est en mode "Suivi Mes adresse" et que je clique sur la croix pour revenir à la France entière, la sélection reste sur la carte
> * Carte : Je ne comprends pas bien les couleurs sur le panneau de gauche je vois des BALs en statut "Publié", Prêt à être publié" et "Brouillon" mais sur la carte tout est bleu ce qui correspond à API formulaire moissonneur.
> 
> <img alt="Capture d’écran 2023-09-07 à 17 52 12" width="404" src="https://user-images.githubusercontent.com/4552238/266373167-9421d85b-d0c7-450a-928c-4aabaa11fa2a.png"> - Liste : Les communes qui n'ont aucune BAL sont légèrement plus foncées que celles qui en ont

- Pour moi on peut le laisser en attendant
- Il y avait bien un problème de colorimétrie sur les epci et département selectionné
- Oui, pour le moment c'est le comportement par defaut 
- Je n'arrive pas a reproduire ca
- Je n'arrive pas a reproduire ca
- Alors oui, c'est étrange à expliquer mais en local il y a surement des décalages entre les infos de adresse (carte) et celle de mes-adresse-api (panel), il faut qu'on voit ca enssemble
-

2023-09-08 13:01 UTC, MaGOs92 commented
Ok après avoir mis les bons Ids je peux voir les couleurs (je préfèrerais qu'on garde les Ids legacy "mes-adresses", "moissonneur-bal", etc... plutôt que des Objects Ids Mongo, c'est plus clair).

Par contre je vois une incohérence : La commune d'Anché a deux BAL en statut "Prête à être publiée", mais sur la carte elle apparait en gris "Ne dispose pas d'une BAL". Normalement sa couleur devrait être bordeaux non?

![Capture d’écran 2023-09-08 à 14 59 47](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/assets/4552238/33b18eb7-000b-4c8e-8690-484accb164ec)

2023-09-11 08:13 UTC, fufeck commented
> Ok après avoir mis les bons Ids je peux voir les couleurs (je préfèrerais qu'on garde les Ids legacy "mes-adresses", "moissonneur-bal", etc... plutôt que des Objects Ids Mongo, c'est plus clair).
> 
> Par contre je vois une incohérence : La commune d'Anché a deux BAL en statut "Prête à être publiée", mais sur la carte elle apparait en gris "Ne dispose pas d'une BAL". Normalement sa couleur devrait être bordeaux non?
> 
> ![Capture d’écran 2023-09-08 à 14 59 47](https://user-images.githubusercontent.com/4552238/266618296-33b18eb7-000b-4c8e-8690-484accb164ec.png)

Il y avait une petite coquille c'est corrigé ;)

2023-09-12 08:46 UTC, MaGOs92 approved these changes
Tests and code LGTM

2023-09-12 09:02 UTC, merged