Add presentation text for API Adresse
BaseAdresseNationale/adresse.data.gouv.fr pull request #1624
Opened 2023-10-03 09:04 UTC by FLoreauIGN

#1529 

L'objectif de cette PR est d'ajouter un texte de présentation de l'API Adresse ainsi que des informations sur que faire si l'on atteint les limites d'appel de l'API.

![image](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/assets/116554403/6f00bba1-65b8-4aba-b60a-dcddc44ca046)

2023-10-03 15:53 UTC, FrederiqWilliams commented
typo 
"d'effectuer rapidement un**e** recherche d'adresse"
expliciter "géocoder"
"mais aussi de pouvoir associer des coordonnées à une adresse ("géocoder") selon plusieurs critères"

2023-10-04 08:42 UTC, antoineludeau requested changes

2023-10-04 08:42 UTC, antoineludeau commented on pages/api-doc/adresse.js
> +        <div className='presentation'>
Ici, className='presentation' n'est pas utile. Ou alors il doit référencer du css qui se trouverait dans un balise <style jsx>{`...`}.

2023-10-04 14:53 UTC, antoineludeau approved these changes
Ok pour moi sur le code. Pour la partie UI, je vous laisse valider.

2023-10-05 15:10 UTC, merged

2023-10-10 14:54 UTC, FrederiqWilliams commented
Le lien "Demander une levée de limite" pointe sur la page de connexion, 
Nous pouvons pointer plutôt directement sur la bonne démarche.
 l'url est : 
https://www.demarches-simplifiees.fr/commencer/demande-de-levee-de-limite-de-l-api-base-adresse