Fix/enable partial download on data
BaseAdresseNationale/adresse.data.gouv.fr pull request #1632
Opened 2023-10-09 16:41 UTC by nkokla

Use module 'send' for set all needed header.

2023-10-10 10:18 UTC, IGNFBourcier approved these changes

2023-10-10 10:18 UTC, IGNFBourcier commented on pages/data/[[...path]].js
> -    }))
plus de tracking ? (en filtrant, si range, sur que les demandes de début de fichier )

2023-10-10 10:18 UTC, IGNFBourcier commented on pages/data/[[...path]].js
> -    context.res.setHeader('Content-Disposition', `attachment; filename="${targetFileName}"`)
plus de force download donc ?

2023-10-10 14:59 UTC, nkokla commented on pages/data/[[...path]].js
> -    context.res.setHeader('Content-Disposition', `attachment; filename="${targetFileName}"`)
Ha si, je dois pouvoir le fournir en option.

2023-10-11 11:06 UTC, nkokla commented on pages/data/[[...path]].js
> -    }))
Bien vu en effet, les script de tracking étaient passé à la trappe.
C'est corrigé.

2023-10-11 11:07 UTC, nkokla commented on pages/data/[[...path]].js
> -    context.res.setHeader('Content-Disposition', `attachment; filename="${targetFileName}"`)
Corrigé également, ils sont maintenant fournis avant le `pipe`à la réponse.

2023-10-11 13:10 UTC, IGNFBourcier requested changes

2023-10-11 14:25 UTC, nkokla commented on pages/data/[[...path]].js
>      sendToTracker(getDownloadTrackData({
Je viens d'ajouter une différenciation avec/sans range.

2023-10-11 14:43 UTC, IGNFBourcier approved these changes

2023-10-11 14:43 UTC, merged