Remplacer Gécodeur actuel par Géocodeur Géoplateforme
BaseAdresseNationale/adresse.data.gouv.fr pull request #1667
Opened 2023-11-23 13:44 UTC by vinsag

Nous souhaitons remplacer le geocodeur actuel par le Géocodeur Géoplateforme IGN sur la barre de recherche et sur la carte.
Il n'y a qu'un changement d'url à faire sur .env

Fix #1662

2023-11-23 15:15 UTC, antoineludeau requested changes
Il y a plusieurs occurrences de "api-adresse.data.gouv.fr" dans le code de adresse.data.gouv qu'il faudrait aussi remplacer

2023-11-23 15:17 UTC, IGNFBourcier commented
Le géocodage de csv n'est pas encore disponible sur la geoplatforme, et cette fonctionnalité est proposée dans les outils :  https://adresse.data.gouv.fr/csv. Utiliser le geocodeur précédent pour cet outil ?

2023-11-23 15:18 UTC, antoineludeau requested changes

2023-11-23 15:18 UTC, antoineludeau commented on .env.sample
> +
```suggestion
NEXT_PUBLIC_API_ADRESSE=https://data.geopf.fr/geocodage
```

2023-11-23 15:18 UTC, antoineludeau commented on .env.sample
> +
C'est du détails mais sur le .env.sample, je ne mettrais que la nouvelle URL.

2024-11-06 12:52 UTC, vinsag commented
On ferme le ticket qui est devenu obsolete, le geocodeur geoplateforme est mis en place sur le nouveau site à venir

2024-11-06 12:52 UTC, closed without merging