Intégration de BAL Widget
BaseAdresseNationale/adresse.data.gouv.fr pull request #1677
Opened 2023-12-08 10:49 UTC by MaGOs92

2023-12-13 12:04 UTC, nkokla requested changes

2023-12-13 12:04 UTC, nkokla commented on hooks/bal-widget.js
> +        document.body.appendChild(script)
Pourquoi passer par un Hook pour faire l'injection de script ? 
(On peut utiliser directement le composant natif de nextJS (https://nextjs.org/docs/pages/api-reference/components/script).

2023-12-13 12:04 UTC, nkokla commented on hooks/bal-widget.js
> +        script.src = `${process.env.NEXT_PUBLIC_BAL_WIDGET_URL}/bal-widget.js`
Sur quoi doit pointer cette URL ? (Pour le moment, j'ai une redirection vers la HomePage du site.)
On peut voir le code de ce script ?

2023-12-13 12:04 UTC, nkokla commented on hooks/bal-widget.js
Le linter relève pas mal de souci. 😅 (Je crois qu'un `yarn lint` permet de fixer ça ou d'avoir le rapport)

2024-01-04 15:10 UTC, MaGOs92 commented on hooks/bal-widget.js
> +        document.body.appendChild(script)
Merci, c'est plus simple comme ça. J'ai supprimé le hook

2024-01-04 15:14 UTC, MaGOs92 commented on hooks/bal-widget.js
> +        script.src = `${process.env.NEXT_PUBLIC_BAL_WIDGET_URL}/bal-widget.js`
Oui, dsl pour le manque de contexte de la PR (j'ai mis à jour la description en haut de page). Voici le code du widget : https://github.com/BaseAdresseNationale/bal-widget

Si tu veux pouvoir tester en local, il faut aussi que tu lances BAL-admin sur cette PR : https://github.com/BaseAdresseNationale/bal-admin/pull/47. (Le widget récupère sa configuration depuis BAL admin)

2024-01-04 15:17 UTC, MaGOs92 commented on hooks/bal-widget.js
> +        script.src = `${process.env.NEXT_PUBLIC_BAL_WIDGET_URL}/bal-widget.js`
Le widget ne sera activé que sur les pages BAL

2024-01-10 11:34 UTC, nkokla commented on hooks/bal-widget.js
> +        script.src = `${process.env.NEXT_PUBLIC_BAL_WIDGET_URL}/bal-widget.js`
Hello !
Il faut que je prenne un peu plus de temps pour tester. (Je regarde ça ASAP).
En dehors des tests, je ne suis pas super à l'aise avec l'idée de passer par une injection XSS pour mettre en place un widget. J'aimerai bien qu'on en parle avant de merger cette branche. Il y a peut-être d'autre possibilité qui pourraient convenir.

2024-05-30 13:33 UTC, nkokla approved these changes

2024-05-30 13:33 UTC, nkokla commented on components/bal-widget/bal-widget.js
> +          setTimeout(() => {
Idéalement, il faudrait également supprimer ce `setTimeout` dans le return du `useEffect`.

2024-05-30 15:28 UTC, MaGOs92 commented on components/bal-widget/bal-widget.js
> +          setTimeout(() => {
Done!

2024-06-04 07:26 UTC, merged