Feat/connect data to s3
BaseAdresseNationale/adresse.data.gouv.fr pull request #1705
Opened 2024-02-26 16:45 UTC by nkokla

2024-02-27 16:57 UTC, antoineludeau commented
Ajouter dans le docker-compose les nouvelles variables. A copier-coller dans le docker-compose.yml à la suite des variables (tout en bas du fichier) : 
      - S3_CONFIG_ACCESS_KEY_ID=${S3_CONFIG_ACCESS_KEY_ID}
      - S3_CONFIG_SECRET_ACCESS_KEY=${S3_CONFIG_SECRET_ACCESS_KEY}
      - S3_CONFIG_REGION=${S3_CONFIG_REGION}
      - S3_CONFIG_ENDPOINT=${S3_CONFIG_ENDPOINT}

2024-02-27 16:58 UTC, antoineludeau commented
Les erreurs que j'ai : 
- Erreur lors de la récupération de la liste des objets : InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
- [27/02/2024 17:53:06 - ERROR] S3 Object - Try access to unknown object: adresse-data/

2024-03-04 09:43 UTC, antoineludeau commented on pages/data/[[...path]].js
> +  endpoint: S3_CONFIG_ENDPOINT,
A tenter avec cette config : 

const s3Config = {
    region: S3_CONFIG_REGION,
    credentials: {
      accessKeyId: S3_CONFIG_ACCESS_KEY_ID,
      secretAccessKey: S3_CONFIG_SECRET_ACCESS_KEY
    },
    endpoint: S3_CONFIG_ENDPOINT,
    forcePathStyle: true,
  }

2024-03-04 10:38 UTC, antoineludeau commented
A tester avec nouvelle structure config : 

const clientS3 = new S3({
  accessKeyId: S3_CONFIG_ACCESS_KEY_ID,
  secretAccessKey: S3_CONFIG_SECRET_ACCESS_KEY,
  region: S3_CONFIG_REGION,
  endpoint: S3_CONFIG_ENDPOINT,
})

2024-03-05 10:27 UTC, mmortier requested changes
J'ai une erreur [05/03/2024 11:22:24 - ERROR] S3 Object - Try access to unknown object: adresse-data/ban/adresses/latest/csv-bal/
Erreur lors de la récupération de la liste des objets : Error: connect ETIMEDOUT 141.95.161.68:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '141.95.161.68',
  port: 443,
  name: 'TimeoutError',
  '$metadata': { attempts: 3, totalRetryDelay: 146 }
}
[05/03/2024 11:22:24 - ERROR] S3 Object - Try access to unknown object: adresse-data/ban/adresses/latest/csv-bal/
wait  - compiling /donnees-nationales (client and server)...
event - compiled client and server successfully in 1350 ms (1081 modules)
wait  - compiling /data/[[...path]]...
event - compiled client and server successfully in 345 ms (1094 modules)

2024-04-16 15:53 UTC, antoineludeau approved these changes

2024-04-16 16:12 UTC, merged