Improved certificate loading state
BaseAdresseNationale/adresse.data.gouv.fr pull request #1823
Opened 2024-09-12 14:24 UTC by antoineludeau

# Context

When a district has its `certificate` feature activated, a link is available on its addresses (that are certified and have an ban id and at least one parcel). When clicking from an address to another on the map explorer, there is a delay and so a desynchronization between the address and the link to download the certificate. 

# Enhancement
 
This PR solves the delay issue adding : 
- a loader,
- a state re-initialisation before getting district data.

2024-09-12 17:11 UTC, jbouhadoun requested changes

2024-09-12 17:11 UTC, jbouhadoun commented on components/base-adresse-nationale/numero/index.js
>                title="Télécharger le Certificat d'adressage"
Il manque le cas où le certificat est actif pour la ville. Par contre, si l'adresse n'a pas de parcelle cadastrale, il faut afficher le message

          <div className='ressource'>
            <div />
            <span>Certificat d&apos;adressage indisponible pour cette adresse, veuillez contacter votre mairie.</span>
          </div>
        )

2024-09-24 13:04 UTC, vinsag commented on components/base-adresse-nationale/numero/index.js
>                title="Télécharger le Certificat d'adressage"
pour tester 8 quai pedros, Bayonne

2024-09-24 15:49 UTC, vinsag approved these changes

2024-09-30 06:40 UTC, vinsag approved these changes

2024-10-02 13:15 UTC, jbouhadoun approved these changes

2024-10-02 13:20 UTC, merged