Vsagniez/geocodeur gpf
BaseAdresseNationale/adresse.data.gouv.fr pull request #1874
Opened 2024-11-06 10:38 UTC by vinsag

- Mise en place du geocodeur Geoplateforme
- Modification page outils
- Changement lien levée de limite sur la page api-adresse

2024-11-06 14:19 UTC, FrederiqWilliams requested changes
Plusieurs remarques à la relecture : 

- titre global de la page : mettre les verbes à l'infinitif : Consulter, contribuer, utiliser la BAN grâce aux différents outils
- titre : mettre "Les outils d'exploitation" à la place de "Les outils de consultation"
- title = API Adresse  : rajouter entre parenthèses: " (en cours de transfert vers le Service de géocodage de la Géoplateforme)
-  'géocoder'  --> ("géocoder")   dans le texte (ligne 69)
- bouton "API Adresse" : il reste des caractères à enlever au début
- Section "Service de géocodage", desc= (ligne 86) : 
- title= "Service de géocodage" : rajouter entre parenthèses :  (Nouveau)
Remplacer par : "Le service Géoplateforme de géocodage permet d’effectuer rapidement une recherche d’adresse, mais aussi de pouvoir associer selon plusieurs critères des coordonnées à une **adresse**, un **point d'intérêt** ou **une parcelle cadastrale**.
- title = "Service d'auto-complétion" : rajouter entre parenthèses : (Nouveau)
- desc = remplacer par "Le service Géoplateforme d’autocomplétion facilite la saisie en suggérant des localisants probables au fur et à mesure de la saisie d’adresses ou de noms de lieux. "
- Supprimer le bloc "Service de géocodage de fichiers"
- Publication d'une base adresse locale : manque le descriptif
- API _dépot_ d'une base adresse _local_ : --> dépôt et --> locale
- desc= API permettant de soumettre une Base Adresse Locale à la Base Adresse Nationale avec les gestions des _habilitions_. --> habilitations
- Faire une nouvelle section "Les outils de la communauté" et y mettre l'explorateur Fantoir et API Fantoir (par la suite  voir PlugIn QGIS + outil TOPO vers Fantoir du CRAIG)
-  renommer "Pour connaitre l'état des outils" par "Les outils de supervision"
- remplacer le bloc "l'état du déploiement BAL" par la page statistiques. Title= les métriques d'impacts

2024-11-06 14:41 UTC, nkokla commented
(poke @FrederiqWilliams )

De mon coté, tout est OK d'un point de vu technique.

Par contre, d'un point de vu UX/Fonctionnel, je troue que ce n'est vraiment pas clair. Certain outils semble faire doublon ou ont une description qui manque de clarté. 

J'aimerai également proposer une autre rubrique pour  les outils déprécié avec un message pour porter l'attention sur le fait que ces outils ne sont plus maintenu (peut-être, pour chaque outils et quand c'est possible, proposer les outils alternatif).

2024-11-06 17:47 UTC, vinsag commented
> Plusieurs remarques à la relecture :
> 
> * titre global de la page : mettre les verbes à l'infinitif : Consulter, contribuer, utiliser la BAN grâce aux différents outils **FAIT**
> * titre : mettre "Les outils d'exploitation" à la place de "Les outils de consultation" **FAIT**
> * title = API Adresse  : rajouter entre parenthèses: " (en cours de transfert vers le Service de géocodage de la Géoplateforme)
> * 'géocoder'  --> ("géocoder")   dans le texte (ligne 69) **FAIT**
> * bouton "API Adresse" : il reste des caractères à enlever au début : **On laisse vu ensemble cet près midi**
> * title= "Service de géocodage" : rajouter entre parenthèses :  (Nouveau) **FAIT**
> * desc= (ligne 86) Remplacer par : "Le service Géoplateforme de géocodage permet d’effectuer rapidement une recherche d’adresse, mais aussi de pouvoir associer selon plusieurs critères des coordonnées à une **adresse**, un **point d'intérêt** ou **une parcelle cadastrale**. **FAIT sauf le texte en gras à voir comment on fait avec le DSFR** @nkokla  si tu as une idée
> * title = "Service d'auto-complétion" : rajouter entre parenthèses : (Nouveau) **FAIT**  Autocomplétion c'est sans tiret
> * desc = remplacer par "Le service Géoplateforme d’autocomplétion facilite la saisie en suggérant des localisants probables au fur et à mesure de la saisie d’adresses ou de noms de lieux. " **FAIT**
> * Supprimer le bloc "Service de géocodage de fichiers" **FAIT**
> * Publication d'une base adresse locale : manque le descriptif
> * API _dépot_ d'une base adresse _local_ : --> dépôt et --> locale **FAIT**
> * desc= API permettant de soumettre une Base Adresse Locale à la Base Adresse Nationale avec les gestions des _habilitions_. --> habilitations **FAIT**
> * Faire une nouvelle section "Les outils de la communauté" et y mettre l'explorateur Fantoir et API Fantoir (par la suite  voir PlugIn QGIS + outil TOPO vers Fantoir du CRAIG) **FAIT**
> * renommer "Pour connaitre l'état des outils" par "Les outils de supervision" **FAIT**
> * remplacer le bloc "l'état du déploiement BAL" par la page statistiques. Title= Les métriques d'impacts **FAIT sauf peut être changer le texte pour statistiques**

2024-11-07 08:07 UTC, FrederiqWilliams commented
Il reste quelques coquilles éditoriales, on peut faire une relecture ensemble mardi

2024-11-07 10:45 UTC, nkokla commented
@FrederiqWilliams Si c'est OK pour toi, tu peux re-valider la PR ? 
Tant que tu ne l'a pas fait, on ne pourra pas la merger. 
Merci 😊

2024-11-07 13:06 UTC, FrederiqWilliams approved these changes

2024-11-07 14:30 UTC, merged