Add page docs
BaseAdresseNationale/adresse.data.gouv.fr pull request #1885
Opened 2024-11-15 13:27 UTC by vinsag

Page documentation

2024-11-15 15:52 UTC, FrederiqWilliams commented
Il faudrait mettre au même niveau d'écriture les sous-titres de la partie 
"Documentation technique BAN" et de la partie "Production de l'adresse". 
réduire les uns ou augmenter les autres

2024-11-15 15:54 UTC, FrederiqWilliams requested changes
Il faudrait mettre au même niveau d'écriture les sous-titres de la partie
"Documentation technique BAN" et de la partie "Production de l'adresse".
réduire les uns ou augmenter les autres

2024-11-15 19:05 UTC, nkokla commented
On a deux PR qui se marche dessus. 
(CF. https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/pull/1887)
Il faut probablement revoir pas mal de chose pour ces pages.

- Mettre en commun les contenus des deux PR.
- C'est la page de doc de la BAN, il faudrait éviter d'y placer les docs des outils (mes-adresse)
- Se mettre en phase avec la maquette mise en place (Il s'agit de la page d'accueil des documentations. Ici, la page est un peu trop rédactionnel pour une page d'accueil.)
- Le contenu mérite probablement d'être revu (ex: titre de la page :"Page documentation" 😅 ) .

2024-12-17 08:08 UTC, FrederiqWilliams approved these changes

2024-12-17 08:18 UTC, merged