feat: add ressource page
BaseAdresseNationale/adresse.data.gouv.fr pull request #1887
Opened 2024-11-15 16:12 UTC by MaGOs92

2024-11-15 17:06 UTC, vinsag requested changes
Il faut discuter de cette page tous ensemble

2024-11-15 18:58 UTC, nkokla commented
On a deux PR qui se marche dessus. 
(CF. https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/pull/1885)
Il faut probablement revoir pas mal de chose pour ces pages.

- Mettre en commun les contenus des deux PR.
- C'est la page de doc de la BAN, il faudrait éviter d'y placer les docs des outils (mes-adresse)
- Rester en phase avec la maquette mise en place (Le Bandeau Hero diffère vraiment trop des autres pages)

2024-11-27 13:58 UTC, vinsag requested changes
Plusieurs commentaires : 
1)Pour rester conforme à la charte graphique sur le bloc hero il faut que l'image dans le bloc hero soit à droite et non à gauche.
2) quand il y a 2 boutons, il faut que le premier soit bleu et le deuxième blanc
3) Est ce volontaire que l'image du haut ne s'affiche pas en mode mobile ?

2024-11-27 17:28 UTC, j-saur approved these changes
lgtm

2024-11-27 17:36 UTC, closed without merging