Modif divers outils
BaseAdresseNationale/adresse.data.gouv.fr pull request #1898
Opened 2024-11-22 14:44 UTC by vinsag

-Ajout lien pour la newsletter dans le menu
** Page outils**
 - Modification lien sur l'explorateur BAN
 - Modification texte
 - Ajout nouvel outil CRAIG dans 'outils de la communauté"

2024-11-22 15:24 UTC, FrederiqWilliams requested changes
nouvel outil mettre plutôt en titre "Convertisseur TOPO - FANTOIR"
description ok, 
et rajouter derrière le terme "CRAIG" le lien sur leur portail : https://www.craig.fr/

2024-11-22 15:48 UTC, vinsag commented
> nouvel outil mettre plutôt en titre "Convertisseur TOPO - FANTOIR" description ok, et rajouter derrière le terme "CRAIG" le lien sur leur portail : https://www.craig.fr/

Je ne peux pas mettre de lien dans la description mais on peut mettre un bouton, en savoir plus sur Craig à coté de documentation

2024-11-25 11:02 UTC, FrederiqWilliams reviewed
manque majuscules à 
Direction (ligne 304) et 
Centre régional et Auvergne-Rhône-Alpes ligne 355

2024-11-25 12:38 UTC, FrederiqWilliams approved these changes

2024-11-25 12:43 UTC, merged