feat: add bal widget navigate event
BaseAdresseNationale/adresse.data.gouv.fr pull request #1919
Opened 2024-12-05 14:37 UTC by MaGOs92

2024-12-06 13:07 UTC, FrederiqWilliams requested changes
C'est nickel merci. 
Une modif svp  : lorsqu'on clique sur le deuxième bouton (rejoindre le collectif), on se retrouve sur une page extérieure au site adresse, sans capacité de reprendre la navigation. Il faudrait donc que cette fenêtre s'ouvre dans un nouvel onglet.

2024-12-10 08:52 UTC, MaGOs92 commented
> C'est nickel merci. Une modif svp : lorsqu'on clique sur le deuxième bouton (rejoindre le collectif), on se retrouve sur une page extérieure au site adresse, sans capacité de reprendre la navigation. Il faudrait donc que cette fenêtre s'ouvre dans un nouvel onglet.

Ok c'est fait

2024-12-10 09:10 UTC, vinsag approved these changes

2024-12-10 09:23 UTC, FrederiqWilliams approved these changes

2024-12-10 09:43 UTC, merged