Ajout d'une section de choix d'outils sur la homepage
BaseAdresseNationale/adresse.data.gouv.fr pull request #921
Opened 2021-11-05 09:45 UTC by Maxine-Le-Pennec

- Suppression de la section sur les Organismes Partenaires

- Remplacée par une section regroupant la barre de recherche des BAN ainsi que des liens vers des outils/informations important.es.

/!\ Utilisation de : 

- MediaQ en respectant les breakpoints imposés. En premier lieu, un grid template permettait de wrapper les éléments suivant la largeur disponible mais le résultat n'était pas assez propre à mon goût. Ils permettent également de supprimer la barre de séparation lors du passage de colonnes à lignes.

- Une div séparatrice au lieu d'un border afin d'avoir un séparateur le plus centré possible

![Capture d’écran 2021-11-05 à 10 35 19](https://user-images.githubusercontent.com/66621960/140490917-90b416f1-2800-41fc-ba32-510cfc80c060.png)

![Capture d’écran 2021-11-05 à 10 44 40](https://user-images.githubusercontent.com/66621960/140491110-790248cd-0583-4d49-a60b-cf139e6c312d.png)

2021-11-05 15:31 UTC, tmerlier requested changes
Je ne suis pas très convaincu par la présentation avec des blocs côte à côte séparé par un divider. Présenter les options l'une en dessous de l'autre me parait plus naturel et plus d'alléger le code.

2021-11-05 15:31 UTC, tmerlier commented on pages/homepage-tools.js
> +import {Database, FileText, MapPin} from 'react-feather'
Attention à l'ordre des imports et le groupement afin de rester homogène avec le reste du code existant.

```suggestion
import Link from 'next/link'
import {Database, FileText, MapPin} from 'react-feather'

import theme from '@/styles/theme'

import BanSearch from '@/components/ban-search'
```

2021-11-05 15:31 UTC, tmerlier commented on pages/index.js
> +import HomepageTools from './homepage-tools'
Le composant `HomepageTools` n'est pas une page, il ne doit donc pas être placé dans `/pages`.

Deux solutions possible en fonction de sa réutilisation:
- `/components/homepage-tools`
- `/components/homepage/tools`

2021-11-10 16:22 UTC, GllmR requested changes

2021-11-10 16:22 UTC, GllmR commented on pages/index.js
> +import HomepageTools from '../components/homepage-tools'
`@/components/homepage-tools`

2021-11-12 08:46 UTC, GllmR approved these changes

2021-11-12 08:47 UTC, merged