Change background with seasons
BaseAdresseNationale/adresse.data.gouv.fr pull request #943
Opened 2021-11-18 17:21 UTC by Maxine-Le-Pennec

- Modification des couleurs directement depuis le svg afin d'éviter toute perte de performance.

### PRINTEMPS
<img width="1080" alt="Capture d’écran 2021-11-18 à 18 11 36" src="https://user-images.githubusercontent.com/66621960/142463686-43bbaa51-4b7c-4b0e-8a1b-62b2f08378ed.png">

### ÉTÉ
<img width="1080" alt="Capture d’écran 2021-11-18 à 18 11 50" src="https://user-images.githubusercontent.com/66621960/142463682-b1d1b54e-3421-48b0-901e-ca602a310590.png">

### AUTOMNE
<img width="1078" alt="Capture d’écran 2021-11-18 à 17 28 59" src="https://user-images.githubusercontent.com/66621960/142463691-5e3696b6-33d0-4622-ba3a-99a5240fc539.png">

### HIVER
<img width="1080" alt="Capture d’écran 2021-11-18 à 17 29 37" src="https://user-images.githubusercontent.com/66621960/142463690-f11f410b-2a17-4f49-97ea-975df59834ab.png">

2021-11-19 16:08 UTC, GllmR approved these changes

2021-11-22 08:41 UTC, tmerlier requested changes
Le fichier `public/images/background.svg` n’est plus utile.

2021-11-22 09:41 UTC, tmerlier approved these changes

2021-11-22 09:43 UTC, tmerlier requested changes

2021-11-22 09:43 UTC, tmerlier commented on components/hero.js
> +/* eslint node/no-unsupported-features/es-syntax: off */
Il faudrait limiter cette règle à la ligne suivante.

2021-11-22 13:15 UTC, tmerlier approved these changes

2021-11-22 13:23 UTC, merged