Améliorer le CSS concernant les partenaires
BaseAdresseNationale/adresse.data.gouv.fr pull request #954
Opened 2021-11-26 11:21 UTC by Maxine-Le-Pennec

Resolve #952

- Uniformiser la taille des logos.
- Améliorer et uniformiser l'espace entre nom et logo.
- Corriger l'affiche en version mobile.

![Capture d’écran 2021-11-26 à 12 03 51](https://user-images.githubusercontent.com/66621960/143573460-8a54a487-4f05-4f58-8f95-835e912d25cd.png)
![Capture d’écran 2021-11-26 à 12 05 26](https://user-images.githubusercontent.com/66621960/143573468-dc859e21-cd77-42d2-a454-a5f7661ad766.png)

2021-11-30 15:32 UTC, GllmR approved these changes

2021-12-01 08:48 UTC, tmerlier commented
Sur la page `/bases-locales`, la section "Quelques partenaires" affiche des logos déformés. Ce qui doit être une erreur localisée car ce problème n'apparait pas sur la liste complète des partenaires.

![Capture d’écran 2021-12-01 à 09 42 16](https://user-images.githubusercontent.com/7040549/144201488-5b2013b9-4414-4176-a315-bc97f78965a8.png)
![Capture d’écran 2021-12-01 à 09 42 41](https://user-images.githubusercontent.com/7040549/144201496-429dca53-0217-43ec-bda4-f872c59109ca.png)

2021-12-01 08:48 UTC, tmerlier commented on components/bases-locales/charte/partner.js
> +import theme from '@/styles/theme'
Pour éviter de répéter `theme.colors`, tu peux aussi importer de cette façon.
```suggestion
import theme, {colors} from '@/styles/theme'
```

2021-12-01 08:50 UTC, tmerlier requested changes

2021-12-01 08:50 UTC, tmerlier commented on components/bases-locales/charte/partner.js
> +          box-shadow: 0px 14px 21px -11px ${theme.boxShadow};
Cette `box-shadow` est peut-être un peu trop appuyée. Quelques chose de plus subtile serait bienvenu d'autant plus que ce n'est que du style.

2021-12-08 13:15 UTC, jdesboeufs commented
@Maxine-Le-Pennec c'est bloqué ici ?

2021-12-13 09:25 UTC, Maxine-Le-Pennec commented
> @Maxine-Le-Pennec c'est bloqué ici ?

Yes, je vois avec Théo

2021-12-14 14:12 UTC, tmerlier approved these changes

2021-12-16 14:47 UTC, merged