Ajout d’une page pour naviguer dans les données FANTOIR
BaseAdresseNationale/adresse.data.gouv.fr pull request #985
Opened 2022-01-04 14:50 UTC by GllmR

Cette PR propose l'ajout d’une page permettant de naviguer dans les données FANTOIR.

Captures : 

![image](https://user-images.githubusercontent.com/56537238/148076508-61fa1593-daf5-4ba8-ad1d-f98defccbcc5.png)

![image](https://user-images.githubusercontent.com/56537238/148076634-d9a112db-1db0-4ed8-9197-ba8f065755f3.png)

2022-01-05 15:27 UTC, tmerlier requested changes

2022-01-05 15:27 UTC, tmerlier commented on lib/api-geo.js
> +}
```suggestion
export async function getDepartements() {
  return _fetch(`${API_GEO_URL}/departements`)
}
```

2022-01-05 15:27 UTC, tmerlier commented on pages/fantoir/index.js
> +  const counties = await getCounties()
Un `try/catch` est nécessaire afin d'évier une erreur `500` au chargement de la page.

De plus, il serait préférable de parler de `departements`, nous avons toujours utilisé les termes français afin d'éviter les ambiguïtés qu'ils pourraient y avoir avec l'anglais.

2022-01-05 15:27 UTC, tmerlier commented on pages/fantoir/index.js
> +  const sortedCounties = sortBy(counties, ['nom'])
Les départements ne changeront pas, on pourrait optimiser en utilisant un `useMemo` ici.
```suggestion
const sortedCounties = useMemo(() => {
    return sortBy(counties, ['nom'])
  }, [counties])```

2022-01-05 15:27 UTC, tmerlier commented on pages/fantoir/index.js
> +              <Link key={county.code} href={`/fantoir/departement/${county.code}`} passHref>
Pourquoi utiliser `passHref` ?

2022-01-05 15:27 UTC, tmerlier commented on lib/api-ban.js
> +  console.log(voieCode)
Un petit oubli.

2022-01-05 15:27 UTC, tmerlier commented on pages/fantoir/departement/[departement]/index.js
> +  }
Sans `try/catch` on risque une erreur `500` au chargement de la page si une des requêtes échoue.

2022-01-05 15:27 UTC, tmerlier commented on pages/fantoir/departement/[departement]/index.js
> +  const departement = departements.find(d => d.code === communes[0].codeDepartement).nom
Ce calcule peut être fait dans le `getInitialProps`.

2022-01-05 15:27 UTC, tmerlier commented on pages/fantoir/departement/[departement]/index.js
> +  const sortedCommunes = sortBy(communes, ['id'])
Tout comme la page départements, cette tri peut être optimisée avec un `useMemo`.

2022-01-05 15:27 UTC, tmerlier commented on components/voie-information.js
> +import theme from '@/styles/theme'
Il manque un saut de ligne.

```suggestion
import {ChevronUp, ChevronDown} from 'react-feather'

import theme from '@/styles/theme'
```

2022-01-05 15:27 UTC, tmerlier commented on pages/fantoir/departement/[departement]/commune/[commune]/index.js
> +  const commune = communes.find(c => c.codeCommune === voies[0].id.slice(0, 5)).nomCommune
`commune` peut être calculée dans `getInitialProps`.

2022-01-05 15:27 UTC, tmerlier commented on pages/fantoir/departement/[departement]/commune/[commune]/index.js
> +  const sortedVoies = sortBy(voies, ['id'])
Tout comme la page départements, cette tri peut être optimisée avec un `useMemo`.

2022-01-05 15:27 UTC, tmerlier commented on pages/fantoir/departement/[departement]/commune/[commune]/index.js
> +  }
Un `try/catch` est nécessaire pour éviter une erreur `500` au chargement de la page.

2022-01-05 15:35 UTC, tmerlier commented on components/voie-information.js
> +        .line {
Un `align-items: center` serait le bienvenu pour aligner tout ça. Il peut être ajouté à tous les `.line` des différentes pages.

2022-01-05 15:37 UTC, tmerlier commented
Il y a pas mal de lignes de code dupliquées pour chaque page. Que ce soit pour les filtres, les debounces ou le style, nous pourrions utiliser des `hooks` et des composants réutilisable pour éviter ce problème.

2022-01-06 07:31 UTC, GllmR commented on pages/fantoir/index.js
> +              <Link key={county.code} href={`/fantoir/departement/${county.code}`} passHref>
```
xo: warning
@next/next/link-passhref - passHref is missing. See https://nextjs.org/docs/messages/link-passhref
```

2022-01-07 16:28 UTC, tmerlier requested changes

2022-01-07 16:28 UTC, tmerlier commented on components/fantoir/body-list-fantoir.js
> +          ))}
```suggestion
          {Object.values(contents).map(value => (
            <div key={uniqueId('_infos')} className='infos'>{value}</div>
          ))}
```

2022-01-07 16:28 UTC, tmerlier commented on pages/fantoir/departement/[departement]/index.js
> +  const departement = departements.find(d => d.code === communes[0].codeDepartement).nom
L'API Géo permet de récupérer directement un département.
```
https://geo.api.gouv.fr/departements/{codeDepartement}
```

2022-01-07 16:28 UTC, tmerlier commented on pages/fantoir/departement/[departement]/index.js
> +        {results?.length > 0 ? (
`results` ne devrait pas pouvoir être `null` ou `undefined`. Cette condition `results?` ne devrait pas être utile.

2022-01-07 16:28 UTC, tmerlier commented on pages/fantoir/departement/[departement]/index.js
> +                link={`/fantoir/departement/${commune.codeDepartement}/commune/${commune.codeCommune}`}
Un `onSelect` serait peut-être plus approprié. Il pourrait ressembler à ça :
```
onSelect={() => Router.push(`/fantoir/departement/${commune.codeDepartement}/commune/${commune.codeCommune}`)}
```

2022-01-07 16:28 UTC, tmerlier commented on pages/fantoir/departement/[departement]/commune/[commune]/index.js
> +    commune
```suggestion
    nomCommune
```

2022-01-07 16:28 UTC, tmerlier commented on pages/fantoir/departement/[departement]/commune/[commune]/index.js
> +        {results?.length > 0 ? (
Même constat, `results?` ne devrait pas avoir besoin d'être utilisé.

2022-01-07 16:30 UTC, tmerlier commented on pages/fantoir/index.js
> +              <Link key={county.code} href={`/fantoir/departement/${county.code}`} passHref>
Cette erreur ne correspond pas au code ici. Il faut remplacer ce `<Link />` par un `onClick` qui appellerait `next/router`.

2022-01-07 16:34 UTC, tmerlier commented
Je propose que la barre de recherche fasse la même largeur que le tableau pour rendre les choses plus harmonieuse.
![Capture d’écran 2022-01-07 à 17 32 36](https://user-images.githubusercontent.com/7040549/148575384-ef6b8310-6e31-4dce-88f2-9d5765c9e943.png)

2022-01-07 20:40 UTC, jdesboeufs commented on pages/fantoir/index.js
> +              <Link key={county.code} href={`/fantoir/departement/${county.code}`} passHref>
Quelqu'un peut m'expliquer pourquoi on a besoin de `onClick` et pas d'un simple lien ?

2022-01-07 20:42 UTC, jdesboeufs commented on pages/fantoir/departement/[departement]/commune/[commune]/index.js
> +  const commune = communes.find(c => c.codeCommune === voies[0].id.slice(0, 5)).nomCommune
Attention @tmerlier on doit utiliser les communes telles qu'elles sont dans FANTOIR. Le référentiel n'est pas exactement le même.

2022-01-07 20:44 UTC, jdesboeufs commented
Je pense que tu peux supprimer la colonne "Code région" et trier la liste des départements par code département. C'est plus classique.

2022-01-10 14:03 UTC, tmerlier requested changes

2022-01-10 14:03 UTC, tmerlier commented on pages/fantoir/index.js
> +  const Router = useRouter()
```suggestion
  const router = useRouter()
```

2022-01-11 16:44 UTC, tmerlier approved these changes

2022-01-13 11:06 UTC, merged