Amélioration de l'affichage des infos de contact de mairie
BaseAdresseNationale/adresse.data.gouv.fr pull request #996
Opened 2022-01-10 15:35 UTC by Maxine-Le-Pennec

### **AVANT**
<img width="1423" alt="Capture d’écran 2022-01-10 à 16 26 18" src="https://user-images.githubusercontent.com/66621960/148792975-066acedc-099f-4ec8-b96e-9a99f21ab537.png">

### **APRÈS**
<img width="1427" alt="Capture d’écran 2022-01-10 à 16 25 42" src="https://user-images.githubusercontent.com/66621960/148793051-2c9a7aa1-ad08-4475-bca6-a62592425247.png">
<img width="1389" alt="Capture d’écran 2022-01-10 à 16 25 26" src="https://user-images.githubusercontent.com/66621960/148793063-6ac62584-99f2-401f-bbfd-943a5b0ea9aa.png">

2022-01-12 09:26 UTC, GllmR approved these changes

2022-01-13 09:12 UTC, tmerlier requested changes

2022-01-13 09:12 UTC, tmerlier commented on components/search-commune-contact/mairie-contact.js
> +  const handleHoraireShown = () => {
```suggestion
  const toggleSchedules = () => {
```

2022-01-13 09:12 UTC, tmerlier commented on components/search-commune-contact/mairie-contact.js
> +  const [areHorairesVisible, setAreHorairesVisible] = useState(false)
Gardons l'anglais pour le nom des variables. Seuls les termes concernant les localisations reste en français pour garder les différentes nuances liée à territoire.

2022-01-13 09:12 UTC, tmerlier commented on components/search-commune-contact/mairie-contact.js
> +                  <div key={`${horaire.du}-${horaire.au}`}>
Des clefs risques d'être identique.

2022-01-13 09:12 UTC, tmerlier commented on components/search-commune-contact/mairie-contact.js
> +                        <li key={`${heure.de}-${heure.a}`}>
Des clefs risques d'être identique.

2022-01-14 16:20 UTC, tmerlier approved these changes

2022-01-14 16:21 UTC, merged